### ISSUE TITLE
drag and drop to uploads files via onboarder not compatible with Safari 7.0.3

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1250] opened 2014-11-13 21:30 UTC
# Steps
1. Open a window in Safari in 7.0.3 and navigate to the osf (staging or production)
2. Try to upload a file via the onboarder either via drag and drop or clicking the upload box.

# Expected
I expected that uploading a file via the onboarder should work as it does on other browsers, either with drag and drop or by clicking the box to get an upload prompt.

# Actual
Uploading does not work. Dragging and dropping a file into the upload box redirects and opens the file in the browser (usually for pdf, jpeg, png, etc) or downloads it (doc, ppt). Clicking in the upload box does nothing - no prompt appears and the box is not highlighted.

**Comment by brianjgeiger** [comment] 2015-03-05 20:15
This *might* be fixed with the new version of DropZone recently released.

**Comment by lbanner** [comment] 2015-03-05 22:29
Who's world is DropZone Mr. @brianjgeiger ? .... Help me know to whom to assign :smile_cat:

**Comment by brianjgeiger** [comment] 2015-03-05 22:36
Could be anyone who knows Javascript. Me, @caneruguz, several of the interns. What we should try first is seeing if @caileyfitz or anyone else with the right version of safari can replicate the problem with Dropzone's sample widget at http://www.dropzonejs.com/examples/simple.html

If it doesn't replicate (and the same for #1669 with its browsers), then we should just replace out the script and test all of the places we can drag and drop. That will be a big testing effort, though, so we'll want to put it in a proper release, I expect.

**Comment by lbanner** [comment] 2015-03-05 22:48
TY!

**Comment by brianjgeiger** [comment] 2015-03-06 15:04
So, complicating this and #1669, we have a custom version of Dropzone to fix some bad behavior with folders. I thought we were patching, but that changed a few sprints ago, so just bringing it up to date may require us to have to fix a regression with folder dropping (i.e. we don't want it) at the same time. @sloria has the [custom version of Dropzone](https://github.com/sloria/dropzone/tree/accept-directory) that we are using right now, so we'll probably need to take a look at those changes and see if it will be difficult to apply to the new version.

**Comment by brianjgeiger** [comment] 2015-03-06 15:13
On the plus side, the changes that were made seem like they'll merge into the new version without much trouble, so it might not be too bad to get this going.

**Comment by haoyuchen1992** [comment] 2015-06-03 16:38
I have spent several days on this bug. Unfortunately, I still don't figure out the real cause and solution. But I would like to share my exploration on this bug. 

Firstly, the complexity is mainly because it involves in both Dropzone and Knockout.  Knockout renders the page at the last moment and it makes it really hard to debug. I used IE dev tool to check the code step by step and found that before the rendering of Knockout, the dz-clickable and relevant events had been attached successfully(See picture below). But after rendering of Knockout, all of them disappear.

![screen shot 2015-06-03 at 10 39 22 am](https://cloud.githubusercontent.com/assets/5420789/7963408/9646044e-09e0-11e5-85cd-9f8cf11bba78.png) 

And also I did a step-by-step debugging on both Safari 7 and Safari 8. Safari 7  also has the same thing as IE. And also although the debugging step record of Safari 7 is exactly the same as Safari 8, it suddenly changes at last rendering step of Knockout.
 
Based on the observation above, I  have tried two solutions.
1) Redesign the code without Knockout JS.  But it is also complicated since a lot of small details are relied on Knockout. Consider the overall stability and my limited knowledge on Knockout, I didn't find the way to not use Knockout and gave up the possible solution.

2) Another possible solution is to change the our customized Dropzone JS. Since I ran the Dropzone JS [Simple example](http://www.dropzonejs.com/examples/simple.html) and it does work well on both IE and Safrai. However, when I replace the newest dropzone.js from offical website, the upload area still is not clickable. 

In a summary, this bug is related to the basic rule behind Knockout. I don't find the final solution. But I could think of two possible directions.
1) Don't use Knockout for this upload component.
2) Replace Dropzone JS with other similar libraries.

**Comment by haoyuchen1992** [comment] 2015-08-14 14:48
@nanchen47 I just tested staging for uploading file on Safari 7 (on https://saucelabs.com). It works!!

**Comment by erinmayhood** [comment] 2015-08-21 15:22
@sloria can this be closed?

**Comment by chennan47** [comment] 2015-08-21 15:54
@erinmayhood The fix only solves the uploading file part. However the drag and drop function still doesn't work. I will change the title of the issue.

**Comment by caileyfitz** [comment] 2015-08-21 16:07
@nanchen47 I have Safari 7.0.6 and I am still having the issue with drag and drop

**Comment by chennan47** [comment] 2015-08-21 16:15
@caileyfitz Thanks for the tests. With that said, this issue should remain open.

**Comment by caileyfitz** [comment] 2015-08-21 16:22
@nanchen47 no problem - sorry for the delay!

**Comment by nanchen47** [comment] 2015-08-25 18:05
Close this one since the title and description is out of date. Continue tracking the rest of the problem in https://github.com/CenterForOpenScience/osf.io/issues/4168

**Closed by nanchen47** 2015-08-25 18:05 UTC
Labels: 2 - ready, bug: production, bug: staging, intern, JIRA, priority - high
