### ISSUE TITLE
[staging & production][IE] Unable to upload via click or drag and drop on onboarder

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1669] opened 2015-02-02 16:14 UTC
Reported by @nicipfeiffer on the 0.24 Trello board

Similar to https://github.com/CenterForOpenScience/osf.io/issues/1250

# Steps
(I am using IE 11, Win 8.1 on a VM to test)
1. Go to Onboarder
2. Click to upload file
3. Drag and drop a file for upload

# Expected
The files would be uploaded

# Actual
Click to upload does nothing.
Drag and Drop does not allow the file to be added.

**Comment by brianjgeiger** [comment] 2015-03-05 20:18
The new version of DropZone claims to be compatible with IE 10+ and supposedly falls back gracefully if it is being used by an incompatible browser. http://www.dropzonejs.com/#compatibility

**Comment by lbanner** [comment] 2015-03-05 22:28
This a WaterButler arena, @brianjgeiger  -- @jmcarp have thoughts?

**Comment by brianjgeiger** [comment] 2015-03-05 22:33
No, I believe this is specifically Dropzone, which is the Javascript library we use to do Drag and Drop via the web browser. The new version may or may not fix it. If not, we might either have to submit a bug or a PR to the Dropzone folks.

**Comment by chennan47** [comment] 2015-04-01 20:33
The file page is using the same dropzone as the file page. And I tested on safari that the dropzone on file page works. So it seems not to be a problem of dropzone. Talk with @sloria and tried to log the dropzone element and the knockout binding also seems correct.
![screen shot 2015-04-01 at 4 26 02 pm](https://cloud.githubusercontent.com/assets/4974056/6951793/d8de270e-d88b-11e4-8dde-c4353b909e04.png)

![screen shot 2015-04-01 at 4 27 52 pm](https://cloud.githubusercontent.com/assets/4974056/6951827/176b1f0e-d88c-11e4-87e7-f44cded494b0.png)

![screen shot 2015-04-01 at 4 27 23 pm](https://cloud.githubusercontent.com/assets/4974056/6951821/064d16dc-d88c-11e4-8875-e42b3f596c9a.png)

Also noticed that when double clicking the dropzone area on safari,
![screen shot 2015-04-01 at 4 31 37 pm](https://cloud.githubusercontent.com/assets/4974056/6951937/a6d81a52-d88c-11e4-9e27-9112b93de104.png)
It seems to be something is blocking the dropzone.
Tried to change the z-index of dropzone but it doesn't fix the problem

**Comment by lbanner** [comment] 2015-04-01 23:17
Want to keep digging in here @chennan47 ? TY

**Comment by lbanner** [comment] 2015-05-19 02:53
Looks to be covered/closed in #1232 - Correct @nanchen47 ? If so, let's close this.

**Comment by nicipfeiffer** [comment] 2015-06-26 14:37
@lbanner @sloria This is happening again!

**Comment by lbanner** [comment] 2015-06-26 15:06
@chennan47  --  Can you looks a this again as priority, please. Did we make changes that regressed a fix? Thanks.

**Comment by mfraezz** [comment] 2015-08-03 20:58
Updated [my fork](https://github.com/mfraezz/dropzone/tree/accept-directory) of [our fork](https://github.com/sloria/dropzone/tree/accept-directory) of Dropzone with their latest release, which is supposed to add IE10+ support. It does not work in IE11, unable to test Safari 7.0.3 (see https://github.com/CenterForOpenScience/osf.io/issues/1250). May add regressions.

**Comment by mfraezz** [comment] 2015-08-04 15:44
Preliminary assessment yields that the issue probably stems from either with the fact that it's not in a `<form>`, or because of our knockout bindings. Changing either of these for IE support would be time consuming and very ugly. Further testing has revealed no regressions (at least in FF), but also no additional functionality (Safari 7.0.3 still untested). Also, according to @caileyfitz, this has never worked in IE.

Possible solutions include:
 * fighting with IE for some indefinite period of time (~1 week) in attempt to get this working
 * failing gracefully with an error message (e.g. "We notice you're using IE. Sorry.")
 * hiding onboarder entirely for unsupported browsers.

Any of these would be better than having the onboarder UI present but failing with no messages.

@lbanner @GaryKriebel Thoughts?

**Comment by sloria** [comment] 2015-08-04 15:47
It's possible that the custom elements usage could be causing breakages in IE: http://knockoutjs.com/documentation/component-custom-elements.html#note-custom-elements-and-internet-explorer-6-to-8

**Comment by mfraezz** [comment] 2015-08-04 15:49
That is a possibility, although it's present in IE11.

**Comment by mfraezz** [comment] 2015-08-04 15:52
It does do the data-bind correctly (`click: clearMessages()` hits that function), but something is preventing the file selection dialog.

**Comment by mfraezz** [comment] 2015-08-04 17:03
Also, a `Dropzone` is being attached to the right DOM element. There may be a set of `dropzoneOpts` to feed in that will make it work, but I'm not yet sure about that.

**Comment by mfraezz** [comment] 2015-08-04 20:44
Confirmed that other dropzones (even on the OSF) work with IE. Something about the way dropzone is configured differently in [treebeard](https://github.com/caneruguz/treebeard/blob/develop/dist/treebeard.js#L1624) allows it to work properly.

**Comment by mfraezz** [comment] 2015-08-12 16:26
I added click functionality, but was unable to determine exactly why drag and drop isn't working. I did notice some weird behavior. When a `click` event was already attached to the dropzone element, I added the following via IE's console (`x` is the dropzone, `y`/`asdfasdf` was the textfield immediately below `x`):
![screen shot 2015-08-11 at 16 33 53](https://cloud.githubusercontent.com/assets/5659262/9229518/8b713010-40eb-11e5-8738-775b19dc0204.png)
Clicking on the textfield and dragging a file over it triggered both of `y`'s events, but manually clicking or dragging a file over the dropzone triggered neither of `x`'s events. However, calling `x.click()` did trigger `x`'s log event. Both ways of clicking `x` triggered the file selector event, but only the `.click` call triggered the log event.

I'm not familiar enough with IE to know why this is happening, but @caneruguz fixed something similar in Treebeard a while ago.

**Comment by mfraezz** [comment] 2015-08-14 13:59
This issue is no longer accurate; at next release, users will be able to upload via click, but drag and drop still won't work.

**Comment by lbanner** [comment] 2015-08-14 15:52
Alright @mfraezz -- we'll close with the release of #4021 and, as needed, create a new issue for drag & drop. Thanks.

**Comment by nanchen47** [comment] 2015-08-25 18:06
Close this one since the title and description is out of date. Continue tracking the rest of the problem in #4168

**Closed by nanchen47** 2015-08-25 18:06 UTC
Labels: 2 - ready, bug: production, JIRA, priority - high
