### ISSUE TITLE
[IE] Small window makes navigation behind video

### ISSUE THREAD

**Issue by ginavuu** [CenterForOpenScience/osf.io#2464] opened 2015-04-13 16:18 UTC
Steps
1. Using IE, go to https://osf.io/9ubcv/.
2. Shrink the window's width
3. Click on project navigation

Expected
The drop down menu would drop over the video.

Actual
Only in IE the window drops behind the video.

![navi](https://cloud.githubusercontent.com/assets/11032617/7119875/4211130e-e1d7-11e4-8337-ccd852ad5b98.PNG)

**Comment by lbanner** [comment] 2015-04-13 16:31
@caneruguz  -- Thoughts here?

**Comment by ginavuu** [comment] 2015-04-13 16:32
Seems to be only on IE

**Comment by ticklemepierce** [comment] 2015-05-29 15:09
Unable to reproduce on my Windows virtual machine.

**Comment by geeksnglitter** [comment] 2015-06-03 19:02
I can take a stab at this one. @lbanner @GaryKriebel

**Comment by lbanner** [comment] 2015-06-04 14:15
@geeksnglitter .... If you cannot reproduce (as @ticklemepierce was unable to), we can close this issue for now -- Let us know. TY

**Comment by geeksnglitter** [comment] 2015-06-04 15:00
I can reproduce it. It's real.

**Comment by lbanner** [comment] 2015-06-04 15:03
Thanks -- you got it :smiling_imp:

**Comment by geeksnglitter** [comment] 2015-06-04 18:58
Okay so I think IE 11 fixes the problem. Should I proceed trying to get it to work with IE 10? @GaryKriebel

**Comment by chennan47** [comment] 2015-06-04 19:00
@geeksnglitter go ahead and try with IE10 but anything below IE 9 may not
be worth the time.

**Comment by lbanner** [comment] 2015-06-04 19:18
Yes -- what @chennan47 said.

**Comment by geeksnglitter** [comment] 2015-06-04 21:11
I was wrong - the issue still appears in IE 11 on saucelab, but when I try it on IE 11 on my virtual box virtual machine it does not appear. The same is true from IE10.

**Comment by geeksnglitter** [comment] 2015-06-05 12:53
Can we defer this for now @lbanner? 

On another note, this might be the fix http://stackoverflow.com/questions/2625166/flash-video-playing-on-top-of-everything-else-in-ie7

**Comment by lbanner** [comment] 2015-06-05 12:54
Appreciate the work on this @geeksnglitter -- we'll defer for now.

**Closed by lbanner** 2015-06-05 12:54 UTC
Labels: 4 - working, bug: production, intern, priority - medium, ui
