### ISSUE TITLE
File renaming unsuccessful if multiples of same letter or character entered in succession

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#4010] opened 2015-08-11 20:27 UTC
Reported on Markup-Safe 3 trello board by @nicipfeiffer.

## Steps

1. Log in to osf.io.
2. Navigate to one of your projects.
3. From the dashboard, click into the files widget.
4. Rename one of your files to include two or more of the same characters in succession, like "helloooooo". Try the same thing with a character like angle brackets. Lastly, try to rename a file to be contained in angle brackets (as in the first screen video below).
5. Notice the behavior when you click somewhere outside or elsewhere within the rename field upon making the above changes.

## Expected behavior

I expect all the characters to persist as entered. 

## Actual behavior

However, in the case of the angle brackets, the first angle bracket is stripped and the second angle bracket turns into a less than sign instead of a greater than sign. 

In the case of renaming a file with multiples of the same letter or character (like angle brackets) in succession, you'll notice that one letter / angle bracket disappears upon clicking away from the rename field. Clicking rename at this point does **not** rename the file.

Once you've attempted to rename with multiples of the same letter or character in succession, trying to edit again is unsuccessful and does not save what the user entered. 

Mouse behavior is also strange and I found it difficult to click between the letters in my file name as I was renaming.

## Screen video

**Angle Brackets**

![rename_file](https://cloud.githubusercontent.com/assets/7093086/9205988/3c2eb814-4033-11e5-8636-264fc1c9325f.gif)

**Comment by NatashaRichter** [comment] 2015-08-11 20:36
@caneruguz Here's that strange file renaming bug.

**Comment by jinluyuan** [comment] 2015-08-11 20:37
Duplicate of https://github.com/CenterForOpenScience/osf.io/issues/3386

**Comment by NatashaRichter** [comment] 2015-08-11 20:41
Thank @jinluyuan. I'm going to link your github issue to the relevant trello card on mark-up safe 3 and close this one.

**Closed** 2015-08-11 20:41 UTC
