### ISSUE TITLE
[Staging & Production] Checking off an add-on causes the OSF header to shift to the right

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#2947] opened 2015-06-03 15:50 UTC
### Steps
1. Go to OSF settings
2. Go to "Configure Add-ons"
3. Check the box of any add-on

### Expected behavior
I expected that once the add-on's permissions modal appeared, everything in the background would remain the same.

### Actual behavior
The blue OSF header noticeably shifts to the right when the permissions modal appears. Once the modal is closed, the header shifts back to the original position.

Note: This also occurs in other instances of a modal appearing, such as when forking a project or adding a component. 

(Safari, Chrome, and Firefox)

![github_headermoves](https://cloud.githubusercontent.com/assets/8591162/7964316/17615db8-09e5-11e5-9671-798c3e2fcdbe.gif)

**Comment by revanthkolli** [comment] 2015-06-04 19:55
@jinluyuan I'm using chrome, but I can't seem to replicate this.

**Comment by jinluyuan** [comment] 2015-06-04 20:51
@revanthkolli I tried it on Chrome again, and the issue still exists. I have the latest version. Try another browser, or vary the window size?

**Comment by gkr6sy** [comment] 2015-06-15 14:33
@revanthkolli I have been able to reproduce this. It only occurs on pages long enough for a side bar. What I think is happening is the introduction of the modal removes said side bar and causes the header to readjust its size according to the (slightly) larger page size.

**Comment by GageGaskins** [comment] 2015-06-16 13:34
So this was a known issue with Bootstrap that has supposedly been fixed. Production might be behind on Bootstrap versions that include the fix.

**Comment by caneruguz** [comment] 2015-06-16 13:42
If I'm not mistaken this is the exact replication of this issue: https://github.com/CenterForOpenScience/osf.io/issues/1663

It looks like it can be addressed now from what @GageGaskins  is saying but in the future please search through issues before starting a new one.

**Comment by GageGaskins** [comment] 2015-06-16 14:14
Bootstrap has a fix for this going into their 3.3.5 release, so we don't need to do anything for this until then.

**Comment by lbanner** [comment] 2015-06-16 14:19
OK - "deferring" for now -- @caneruguz can you keep eye on this? Thanks.

**Comment by caneruguz** [comment] 2015-06-16 14:39
@lbanner can you add a UI tag to this? Thanks!

**Closed** 2015-07-22 20:44 UTC
Labels: 1 - deferred, bug: production, bug: staging, priority - low, ui
