### ISSUE TITLE
addons not being listed in file tree

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2768] opened 2015-05-20 15:07 UTC
<h4>Steps</h4>
1. Visit this project: osf.io/amp3e
2. Look at the logs. Note the activity indicating that there are connected Dropbox and Github accounts. 
3. Look at the file tree on the overview. Note that there are no addons listed there.
4. Visit the files page to look at the file tree there as well.

![screen shot 2015-05-20 at 10 47 50 am](https://cloud.githubusercontent.com/assets/4965832/7728827/5ae10194-fedf-11e4-830b-04fc47211d7e.png)

<h4>Expected</h4>
1. Unless the history notes that an addon has been removed, it should be listed in the file tree for the project. 
2. 

<h4>Outcome</h4>
1. No addons or addon files are listed in the file tree, despite logs indicating that there should be.
2. @sloria noted that the database indicates that Github and Dropbox are active for this project.

I was unable to reproduce this on staging. I tried registering the project as well, but the original project still showed the Dropbox addon. I have also confirmed that deauthorizing an addon does produce a log.

**Comment by lbanner** [comment] 2015-05-20 15:11
@jlcohoon Two questions: Is this specific to this project? or can you reproduce / have you seen on others? - and: What happens if the add-on is part of the 'private' component? Is functionality such that logs only represent activity on the 'parent?' Thanks.

**Comment by jlcohoon** [comment] 2015-05-20 15:20
I haven't found another project that this is occurring for, though I've
found a limited number of projects with addons. It's possible it's specific
to this one project, but I can't be sure.

And no, this isn't occurring because of a private component. Logs for
private components are not shown in a public parent (I tested and confirmed
this to be sure this isn't a privacy issue).

**Comment by jlcohoon** [comment] 2015-05-29 14:41
another project that this occurs for: https://osf.io/ag5tn/

**Comment by chennan47** [comment] 2015-05-29 14:46
for https://osf.io/ag5tn/ from the log, the user just added all the addons
but never authored them. It is expected no addons are showing up.

**Comment by jlcohoon** [comment] 2015-05-29 14:58
But the widget shouldn't show up on the overview if the addon isn't completely configured, no?

**Comment by chennan47** [comment] 2015-05-29 15:02
The widget will show up as soon as you enable that addon, which maybe not a
proper behavior.

**Comment by samanehsan** [comment] 2015-06-10 19:10
It makes sense to me that you only see an add-on icon in the files grid if you've both selected and configured it, because the configuration step involves selecting a folder/repo. Ok to close this since it's expected behavior? @jlcohoon, @chennan47, @lbanner, @GaryKriebel

**Comment by lbanner** [comment] 2015-06-10 19:15
Yes -- if that is current functionality. I'll close.

**Closed by lbanner** 2015-06-10 19:15 UTC
Labels: 2 - ready, bug: production
