### ISSUE TITLE
[staging & production] IE: Bootbox causes page to jump

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1675] opened 2015-02-02 16:30 UTC
Reported by @nicipfeiffer on the 0.24 Trello board

## Steps - using IE
1. Go to the user profile page
2. Click on the gravatar image
3. when the gravatar info modal pops up, hit ok
4. click the gravatar again

## Expected
The page would remain stable

## Actual 
The page jumps when clicking on the gravatar. 
![profile_shift](https://cloud.githubusercontent.com/assets/5975444/6004172/d65bc4fe-aace-11e4-9e6b-7981dc37afbe.gif)

Additional info from @nicipfeiffer: "Found that this also occurs with IE when importing access tokens and deauthorizing add-ons."

**Comment by brianjgeiger** [comment] 2015-02-02 21:23
Duplicate of #1663.

**Closed by brianjgeiger** 2015-02-02 21:23 UTC

**Comment by caneruguz** [comment] 2015-02-02 21:38
Here's the culprit: When the modal opens body gets the .modal-open class which removes scrolling, in effect removing the scroll bar. When the scroll bar is an overlay no width change happens but otherwise this bug takes place. I think this is a bug with bootstrap. 

![screen shot 2015-02-02 at 4 37 27 pm](https://cloud.githubusercontent.com/assets/1314003/6009682/f5588bd2-aaf9-11e4-90f4-6becae633392.png)

**Comment by caneruguz** [comment] 2015-02-02 21:42
https://github.com/twbs/bootstrap/issues/9855

**Comment by lbanner** [comment] 2015-02-02 21:47
@caneruguz Same culprit for #1663? @brianjgeiger closed this one in favor of that one - Thanks!

**Comment by caneruguz** [comment] 2015-02-02 21:50
Yes it looks the same, although I can't confirm because my Mac OS puts overlay to all scrolls. The better description for this issue is #1663, we should keep that one open and close this one or defer this one.

**Comment by lbanner** [comment] 2015-02-02 21:54
Agreed -- and you are assigned to #1663 -- Thanks!
