### ISSUE TITLE
[production] file view page search does not consistently redraw w/ github

### ISSUE THREAD

**Issue by icereval** [CenterForOpenScience/osf.io#2591] opened 2015-04-27 05:04 UTC
Steps
===

Create a project.
Attach a Github repository w/ multiple files.
Select a file to view in the file view page.
Search for a specific file in your github repository.
Backspace the search one character at a time and note the github repo does not redraw as expected.
Hitting backspace after the last character has been removed will cause a redraw.

Expected
===

File search shows results of user input

Actual
===

![file search](https://cloud.githubusercontent.com/assets/3111541/7341930/f3af8798-ec5f-11e4-9e30-2939c9a47245.gif)

**Comment by lbanner** [comment] 2015-05-29 02:44
@caneruguz ... have you had opportunity to replicate / dig-in on this one?

**Comment by caneruguz** [comment] 2015-05-29 13:33
@icereval @lbanner  
The github list is doing what it's supposed to be doing, it matches the remaining characters, fa, then f, etc. and there aren't many of those in the github repo as far as I can see. 

I discovered an unrelated error in looking at this but I don't see what's wrong here. Can someone spell it out for me?

**Comment by lbanner** [comment] 2015-05-29 13:59
At this point, if not reproducible as an issue, I'd suggest closing this one -- any debate?

**Comment by samanehsan** [comment] 2015-06-10 19:23
@icereval okay to close?

**Comment by icereval** [comment] 2015-06-11 03:10
I can still reproduce this on the file view page, however the only difference is i can type `fab` and backspace to `f` and it will only show two items the file tree, as a workaround moving the scroll redraws the rest of the elements. It might be easier to demonstrate this in person.

@samanehsan @caneruguz

**Comment by mfraezz** [comment] 2015-07-08 18:09
I'm unable to reproduce this on staging with my fork of the MFR. Fangorn changes frequently enough that this was probably fixed in the past four weeks, perhaps incidentally.

**Comment by lbanner** [comment] 2015-07-08 18:11
@icereval ... ?

**Closed** 2016-03-09 16:56 UTC
Labels: 2 - ready, bug: production, priority - medium, ui
