### ISSUE TITLE
adjusting column width in rendered csv file does not reveal clipped content

### ISSUE THREAD

**Issue by TomHardwicke** [CenterForOpenScience/osf.io#3817] opened 2015-07-25 15:58 UTC
# Steps 
1. Uploaded a .csv file to my (private) OSF project. One column (stream) contains very long character strings e.g., "['4', '1', '3', '2', '4', '4', '1', '3', '2', '4', '4', '1', '3', '2', '4', '4', '1', '3', '2', '4', '4', '1', '3', '2', '4', '4" etc  

2. The content does not fit the column so it has been clipped, see below:

![screen shot 2015-07-25 at 16 48 52](https://cloud.githubusercontent.com/assets/5615147/8890142/29595148-32ed-11e5-9a36-f5b1dd493578.png)
3. I attempted to see more of the clipped content by adjusting the column width.

# Expected
To see more of the clipped content as the column was expanded. Content should not overflow into other columns.

# Actual
Expanding the column width does not reveal the clipped content, see below:

![screen shot 2015-07-25 at 16 52 24](https://cloud.githubusercontent.com/assets/5615147/8890157/ca63278a-32ed-11e5-8169-c1ec710eb742.png)

**EDIT** I have just noticed that the issue is worse - the content of the stream column has 'overflowed' into subsequent columns (notice for example that the gender column contains numbers - it should actually only contain either 'F' or 'M'. Speed, errors, accuracy and age columns are also incorrectly displayed). I have downloaded the file and double checked in Excel - it is not a problem with the file.

**Comment by lbanner** [comment] 2015-07-27 18:19
@icereval ? @mfraezz ? --- Can we look into this as a priority? MFR related? Thanks.

**Comment by mfraezz** [comment] 2015-07-27 20:01
I think I know what's going on. It's a comma separated value file, and string in *stream* contains commas. Either pandas (the library we use to render .csv's) doesn't ignore commas that are inside quotation marks, or some of the preprocessing we're doing to hide comments from the rendering is messing with the quotes. My guess is the former, but I'll investigate further.

**Comment by lbanner** [comment] 2015-07-27 20:16
Thanks @mfraezz -- Tagging you with this.

**Comment by mfraezz** [comment] 2015-07-27 21:47
Correction: we're using the python stdlib csv tools. Turns out, the auto-sniffed dialect being passed to the csv reader, for whatever reason, causes this bug. Using the default dialect (excel) fixes this, and probably doesn't break anything else. I'm going to do a bit more testing first, will have a PR up tomorrow.

<img width="1026" alt="screen shot 2015-07-27 at 17 45 11" src="https://cloud.githubusercontent.com/assets/5659262/8918657/535b55a4-3487-11e5-822e-10daefe43889.png">

**Comment by mfraezz** [comment] 2015-07-28 14:54
So the actual problem, at least with my attempt to reproduce this issue, is that with so many single-quote chars (wrapping the items in the *stream* array), the sniffer detects ' to be the quotechar, rather than ", which is wrapping the entire cell.

@TomHardwicke could you please email (matt@cos) or provide me a link to the csv in question? I just want to confirm that the formatting is the same between yours and my test file. If it is, the PR I'm about to reference will fix.

**Comment by TomHardwicke** [comment] 2015-07-29 09:05
I have e-mailed you the csv file Matt - thank you for looking into this.

**Comment by mfraezz** [comment] 2015-07-29 14:03
Thanks. Formatting was a bit different, but I generalized it better with regular expressions. Now your data is rendering properly for me: 
<img width="875" alt="screen shot 2015-07-29 at 09 59 23" src="https://cloud.githubusercontent.com/assets/5659262/8959414/bb9998d6-35d8-11e5-8efd-89ea426afe26.png">

**Comment by TomHardwicke** [comment] 2015-08-05 14:57
That looks correct. The fix has not been applied yet thought right? I'm still getting the same issue on my OSF project.

**Comment by lbanner** [comment] 2015-08-05 19:08
@sloria @mfraezz --- when ready, can we Hot Fix this?

**Comment by mfraezz** [comment] 2015-08-06 16:02
@TomHardwicke That's correct. It's ready to be merged, but it likely won't be fixed on production until Monday (our lead devops guy is at a conference). If you need it for an important presentation or something before then, we might be able to have it deployed, but that's not something I personally have control over.

**Comment by TomHardwicke** [comment] 2015-08-06 16:09
Hi @mfraezz Ok that's great - we're about to submit a paper and we expect the reviewers might want to take a look at the OSF project. If its sorted by Monday then that would be perfect.

**Comment by mfraezz** [comment] 2015-08-10 18:15
@TomHardwicke This should be fixed now, can you confirm? If so, @lbanner can you close this issue. It was merged as a hotfix

**Comment by lbanner** [comment] 2015-08-10 18:30
Great! -- @TomHardwicke just let me know. Thanks.

**Comment by TomHardwicke** [comment] 2015-08-17 16:40
@lbanner Sorry for delay responding - yes this is fixed thanks very much guys!

**Comment by lbanner** [comment] 2015-08-17 17:46
Excellent @TomHardwicke -- Hope all is well with you. Thanks.

**Closed by lbanner** 2015-08-17 17:46 UTC
Labels: 5 - pending review, bug: production, community, priority - high
