### ISSUE TITLE
[Production & Staging] User name updating inconsistencies

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2565] opened 2015-04-22 16:06 UTC
## Steps for Project/Registration
1. Log in to osf.io
2. Go to a public project you have admin on.
3. Upload a file to OSF storage
4. Make a registration of the project
5. Go to the User Settings page/Profile Information
6. Make a change to your last name in the Full Name field, Submit.
![screenshot 2015-04-22 11 32 50](https://cloud.githubusercontent.com/assets/9381062/7278423/69d73428-e8e3-11e4-970e-b14c384f686a.png)
7. Refresh the page and see the changes take effect in the upper right
8. Go back to the public project that you are admin on where you did steps 2-4.
9. On the project overview page see that the project log is updated with the new name, also that the Contributor list is updated with the changed last name.

## Steps for Search
10. Click on the magnifying glass in the navbar and enter the public project name to search
11. Notice the Contributors listed on the project (will see the older last name listed, not the updated)
12. Click on the project to go to the project
13. Click on the registrations tab
14. Notice the last name on the registration just made (will see the older last name listed, not the updated)
15. Click on the recent registration and look at the contributor list (will now see the updated last name)
16. Click on the magnifying glass to search, enter the project name
17. Click to see registrations filtered in results returned
18. Notice the Contributors listed on the registration of the project (will see the older last name listed, not the updated)

## Expected
The user name is updated on the project log and project overview page with contributor list.
![screenshot 2015-04-22 11 40 46](https://cloud.githubusercontent.com/assets/9381062/7278609/846b6b00-e8e4-11e4-9a53-a0d41879a0f9.png)
It should be updated everywhere.

## Actual
The updated user name is not updated on search results
![screenshot 2015-04-22 11 39 24](https://cloud.githubusercontent.com/assets/9381062/7278574/5c64f2ca-e8e4-11e4-9ca3-bdd2a6721b3f.png)

For registrations, the updated last name should be listed as the updated version on the registration tab of the project, the registration itself in the contributor list and when found in search results.  It is only updated when on the registration overview page.
![screenshot 2015-04-22 11 53 47](https://cloud.githubusercontent.com/assets/9381062/7278900/46c30392-e8e6-11e4-8b23-71c6a21f1e29.png)
![screenshot 2015-04-22 11 54 14](https://cloud.githubusercontent.com/assets/9381062/7278918/5a4070ee-e8e6-11e4-9ac8-dd8d3a58bc69.png)
![screenshot 2015-04-22 11 55 40](https://cloud.githubusercontent.com/assets/9381062/7278941/8851c776-e8e6-11e4-82cf-231ee8497329.png)

Also, @caileyfitz explored this and is seeing the same inconsistencies.

**Comment by GaryKriebel** [comment] 2015-05-12 03:36
@fabianvf how quickly should elasticsearch have these updates?

**Comment by fabianvf** [comment] 2015-05-12 13:30
Search engine should be tracking all of this as it happens. Something may have broken the update logic.

**Comment by ticklemepierce** [comment] 2015-05-20 14:39
As far as I can tell (correct me if I'm wrong), the name that shows up in search is the name when the project was created and the file uploads and registrations are not necessary to reproduce the issue.  @nicipfeiffer can you check this and confirm if you get a chance?

**Comment by nicipfeiffer** [comment] 2015-05-20 17:31
@ticklemepierce You would need the step for making a registration so that you have a registration to look at the 'Steps for Search' 4-9, unless I have misunderstood your question.

**Comment by samanehsan** [comment] 2015-06-03 14:54
@nicipfeiffer, I think the reason the name was not updated on the list of registrations was because it pulls from your given, middle and family name instead of your full name. It's the same thing with the component widgets. Maybe check if those are different?

**Comment by samanehsan** [comment] 2015-06-03 15:15
This issue has been previously reported in #1237

**Comment by lyndsysimon** [comment] 2015-06-04 14:21
Closing in favor of #1237.

**Closed by lyndsysimon** 2015-06-04 14:21 UTC
Labels: 5 - pending review, bug: production, intern, priority - high
