### ISSUE TITLE
Go/nogo for release 0.40.0

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/osf.io#3164] opened 2015-06-17 13:50 UTC
This release includes registration embargoes, retractions, and archiver.

Downtime is expected to be minimal, though we'll want to do a quick, constrained regression test immediately after release.

@JeffSpies @lbanner @GaryKriebel @icereval @nicipfeiffer @caileyfitz

**Comment by sloria** [comment] 2015-06-17 19:43
I am a go once the remaining bug cards are resolved and tested. Re: the dataverse/figshare bug, @lbanner and I suggested removing archiver support for those addons for now.

**Comment by lbanner** [comment] 2015-06-17 19:45
I am a "GO" as well, given those parameters.

**Comment by GaryKriebel** [comment] 2015-06-17 19:47
Will there be notice given to the user that there will not be dataverse/figshare support?

**Comment by sloria** [comment] 2015-06-17 19:47
@GaryKriebel Yes

**Comment by GaryKriebel** [comment] 2015-06-17 19:48
With @sloria confirmation on my question and when the bug cards are cleared, I'm a go as well.

**Comment by nicipfeiffer** [comment] 2015-06-17 20:19
I am a GO once all the bugs have been tested by the QA team and marked as 'resolved/ready for production'.

**Comment by caileyfitz** [comment] 2015-06-17 20:21
I'm a **go** once all trello cards (bugs) have been cleared out

**Comment by chrisseto** [comment] 2015-06-17 21:03
Figshare we can tell if it is archivable or not in a single request, which I think would be an easy enough change albeit a bit hacky given the current architecture.
Dataverse should be fine to copy from at any point in time and I'm not certain as to why we are deferring putting it in archiver. I also don't know why it's failing, if anyone could shed some light on that it would be very appreciated.

I was not pinged in the go/no go my my opinion is *no go* for the moment.

**Comment by lbanner** [comment] 2015-06-17 21:09
@chrisseto I will default to the group, but here is my thinking: complexities clearly exist in Dataverse and figshare -- and we are near 2 weeks behind on this release. If we hold to continue to deal with those two add-ons, we may not release the greater value here for another few days to a week. I'd suggest the iterative approach, we get what is stable to Production and release Embargoes/Retractions, then bring those other two add-ons on board when issues are resolved.

**Comment by chrisseto** [comment] 2015-06-17 21:19
@lbanner I, personally, dont think that adding in figshare will add any complexity it appears to be a simple fix that. I'd be fine hotfixing tomorrow.
Dataverse is what makes me nervous. As far as I know we do not know why it fails, which is red flag to me. If someone can answer that well I'll be a go.

**Comment by JeffSpies** [comment] 2015-06-17 21:53
I'm hesitant to release if we don't know why dataverse is failing. That suggests that we may not have complete knowledge about the rest of the system.

For the regression plan, I also suggest more explicit titles like "OSF System Test Registration".

**Comment by sloria** [comment] 2015-06-17 22:13
Chris makes a valid point; we should understand why Dataverse is failing--and ensure that it is not happening with other add-ons.

It would be advantageous to release when we have the QA team in-office and available for regression testing immediately after release.

Delaying release will not hold back QA: they will be able to begin testing on 0.41.0 in the morning tomorrow.

**Comment by sloria** [comment] 2015-06-17 22:18
Also, there are a few last things to resolve and test, such as cleaning up of failed registrations.

**Comment by sloria** [comment] 2015-06-17 22:18
So I'm a nogo for now.

**Comment by lbanner** [comment] 2015-06-17 22:19
To be clear: If we make any fixes to add-ons, Figshare or Dataverse, and the Archiver code, it will require at minimum a pass through of QA for those add-ons, and possibly wise to do a general pass on full Archiver/Embargo/Retraction. That's OK if we have some hesitancy, but we will be looking at QA process on 0.40.0 again tomorrow.

**Comment by sloria** [comment] 2015-06-17 22:23
That is inevitable--even if we release early, QA will have to go through additional passes after hotfixes are made. The only difference is that they would have test on production, which we want to avoid, esp. with registrations.

**Comment by caileyfitz** [comment] 2015-06-17 22:36
My thoughts:

- @sloria makes a really good point about testing hotfixes -- that would necessitate making test registrations on production, which we really want to avoid given that they are always public and also released as SHARE events.

- @nicipfeiffer and I have had some strange happenings that are due to unknown causes and seem to be rare (but still really important). Since we are making a big promise with archiver and imposing an ultimatum on users, we want to make sure that we are as certain as we can be about when we expect failures to happen vs not

- I have also found an additional bug regarding HTML escapes that does definitely need to be resolved before we release. 

With this all in mind, I am now a no go :no_entry_sign: :rocket:

**Comment by lbanner** [comment] 2015-06-17 22:40
OK .... I'm with you. Not to belabor one point, however :smiling_imp: I would not have suggested any work/fixes to bring Figshare or Dataverse up-to-date after this release as hotfixes, rather would have worked those changes thru the regular Review--Staging--QA--Release process.

**Comment by JeffSpies** [comment] 2015-06-18 02:19
OK, no go. I'd also like to talk more about regression testing tomorrow.

**Comment by sloria** [comment] 2015-06-18 12:27
Re-ping @JeffSpies @GaryKriebel @lbanner @icereval @caileyfitz @nicipfeiffer @chrisseto 

Goal is to understand and resolve the issues with figshare and dataverse, discuss regression testing, address remaining bugs found, test cleanup of failed registrations, and release at **4:00 pm**, followed by regression testing.

**Comment by GaryKriebel** [comment] 2015-06-18 12:35
Let's all meet after standup.

**Comment by sloria** [comment] 2015-06-18 21:18
I am go once the remaining cards are through and QA is a go.

**Comment by lbanner** [comment] 2015-06-18 21:20
OK -- I am a "go" under that parameter as well -- Looks like only the one issue remaining ...

**Comment by GaryKriebel** [comment] 2015-06-18 21:20
Ditto

**Comment by chrisseto** [comment] 2015-06-18 21:34
I am a **go**

**Comment by sloria** [comment] 2015-06-18 21:53
There is an issue that is causing projects with multiple addons to probabilistically fail. I am nogo until this is resolved.

**Comment by nicipfeiffer** [comment] 2015-06-18 22:14
I am also a no-go.  There are still problems with add-ons and unsuccessful registrations.  We need to have this working consistently before I am a go for release.

**Comment by lbanner** [comment] 2015-06-18 22:29
OK ... NoGo ... appreciate all the work put in trying to figure this one out.

**Comment by sloria** [comment] 2015-06-19 13:36
Re-ping @JeffSpies @GaryKriebel @lbanner @icereval @caileyfitz @nicipfeiffer @chrisseto

We are currently working on figuring out why registrations are probabilistically failing. 

Again, target release time is **4:00pm**.

**Comment by GaryKriebel** [comment] 2015-06-19 13:44
I will provide a go/no go closer to 4pm

**Comment by lbanner** [comment] 2015-06-19 14:06
I'll note a discomfort with a 4:00pm Friday release -- and might propose Sunday evening, giving us Monday AM for regression. I'll continue to check-in on progress. Let @GaryKriebel and I know if we can help w/resource.

**Comment by sloria** [comment] 2015-06-19 19:30
Sam and Chris have put in a fix to support archiving both Unpublished and Published versions of dataverses, which may be part or all of the cause of the probabilistic registration failures we were seeing yesterday. I seem to recall QA @WillBanner seeing failures without Dataverse, though.

QA will see if they can reproduce the failures. 

I am a go once we demonstrate that registrations succeed reliably. 

@lbanner raises a valid point re: release time, esp. with Michael and Chris out this weekend. I am fine with a Sunday evening release date.

**Comment by JeffSpies** [comment] 2015-06-19 19:32
You're busy too this weekend, Steve. Let's go a bit later if necessary.

**Comment by lbanner** [comment] 2015-06-21 22:57
Hey @sloria ... Staging up-to-date with latest fixes? Wondering if worthwhile to get QA on for some runs this evening, with possible deploy night or morning? Let us know your thoughts on this. Thanks.

**Comment by sloria** [comment] 2015-06-22 00:31
Yes, staging has been up to date with Sam's most recent fixes.

@caileyfitz @GaryKriebel @nicipfeiffer Have you been able to produce any registration failures since Friday?

**Comment by GaryKriebel** [comment] 2015-06-22 00:53
I'll give it a go again now.

**Comment by GaryKriebel** [comment] 2015-06-22 01:23
I just registered my big monster project with no issues 6 times (3 regular registrations, 3 embargos).

**Comment by lbanner** [comment] 2015-06-22 01:25
@WillBanner and I are cranking some registrations -- so far so good.

**Comment by WillBanner** [comment] 2015-06-22 01:28
Just registered a project that had all add ons with 5 components that also
had all add ons

**Comment by sloria** [comment] 2015-06-22 01:38
Re-ping @JeffSpies @GaryKriebel @lbanner @icereval @caileyfitz @nicipfeiffer @chrisseto for go/nogo

**Comment by GaryKriebel** [comment] 2015-06-22 01:40
from what i have seen, i'm a go

**Comment by lbanner** [comment] 2015-06-22 01:57
Got a couple stuck in archiving @sloria -- will let you know if they pull thru ...

**Comment by GaryKriebel** [comment] 2015-06-22 01:58
Mine took some time.... lots of files.

**Comment by lbanner** [comment] 2015-06-22 02:22
OK -- one success -- one failure w/notification: OSF storage + GoogleDrive + 2 Components. Notification attached.
![screen shot 2015-06-21 at 10 19 10 pm](https://cloud.githubusercontent.com/assets/2964829/8274689/00ce3930-1864-11e5-9e5c-9631a08dad48.png)

**Comment by lbanner** [comment] 2015-06-22 02:24
The notification is a positive, and no obstacle to deployment, I think -- However, @sloria ... any backend capture of failures? So desk/community is able to respond as needed?

**Comment by sloria** [comment] 2015-06-22 02:46
@lbanner Yes, I see the failure notification on Desk.com--does that project consistently fail to register?

**Comment by lbanner** [comment] 2015-06-22 02:52
First time to register -- First time to fail. A failure w/notification is proper functionality. Maybe I remove a component or two, and try again -- But as long as the communication on failure is working as it should -- I am still a "Go" on release given all other tests.

**Comment by lbanner** [comment] 2015-06-22 03:03
FYI: This project failed again on Registration w/notification. Now includes OSF storage + GoogleDrive + one basic component w/OSF storage. The GoogleDrive add-ons is tied to our shared Infrastructure Proposals Folder (may be some unknown complexities there) ... unless anyone else is running into issues, I remain good-to-go.

**Comment by JeffSpies** [comment] 2015-06-22 13:15
I'll wave decision making on this one.

**Comment by sloria** [comment] 2015-06-22 14:08
The following items need to be resolved before release:

- Disallow retraction of subprojects/components in isolation. Harry is working on this now. This should resolve the 2 remaining Trello cards
- Deploy waterbutler update to fix registering Dataverse Published+Unpublished files. Chris is working on this.
- Address CAS errors happening on files pages on staging

Target is to deploy at 4pm today.

**Comment by sloria** [comment] 2015-06-22 19:47
We've completed testing the embargo and retraction scenarios and scripts.

Sam's fixes for the two remaining trello bugs are ready for QA.

Once those are resolved and QA gives the go-ahead, I am a go.

**Comment by lbanner** [comment] 2015-06-22 19:49
With those resolved, yes, I am a "GO" --

**Comment by caileyfitz** [comment] 2015-06-22 19:49
Once QA checks Sam's fixes, I am a GO

**Comment by GaryKriebel** [comment] 2015-06-22 20:51
I will defer to @caileyfitz and @sloria

**Comment by sloria** [comment] 2015-06-22 21:03
Looking into one last issue with Dataverse draft files. Once that is resolved, I think we are a go.

ping @chrisseto and @icereval for go/nogo

**Comment by chrisseto** [comment] 2015-06-22 21:14
@sloria @samchrisinger And I are looking into this now.

**Comment by lbanner** [comment] 2015-06-22 21:18
:+1: Thanks.

**Comment by caileyfitz** [comment] 2015-06-22 21:20
For the time being, I am a no-go. Will reassess later this evening. Having too many Dataverse issues (differences in archiving content based on registration timing) that were thought to be fixed but are now appearing again.

**Comment by lbanner** [comment] 2015-06-22 21:39
We are a full week beyond the date it was thought we could resolve Figshare and Dataverse within a day or so -- I'd like not to head down that path again. If we need to simply disallow Dataverse registration in order to bring the high-value of Archiver/Retraction/Embargo to our user base now (expected June 8), then I believe we should make the decision to do so. As I noted last week, Dataverse can then be brought on as an enhancement later, once issues are settled.

**Comment by sloria** [comment] 2015-06-22 22:02
Not sure if it is more work to disable Dataverse (and add necessary language for the user, etc.) or to fix the existing issue: @chrisseto is probably in the best position to assess.

**Comment by chrisseto** [comment] 2015-06-22 22:17
I'm going to defer to @samchrisinger as he is the most up to date with his progress.
I believe there is only one unanswered bug at this point.

**Comment by samchrisinger** [comment] 2015-06-23 00:42
With the most recent updates to staging Dataverse is working as expected. Once QA takes a final pass I'm a go.

**Comment by GaryKriebel** [comment] 2015-06-23 02:00
Looks like I'm a go.  Anyone else?

**Comment by lbanner** [comment] 2015-06-23 02:20
"Go" also ... when you are ready @sloria  -- and thanks much for dedicated work @samchrisinger .... @caileyfitz ?

**Comment by caileyfitz** [comment] 2015-06-23 03:19
Sorry - was snoozing 😴 After a rough sanity check on a couple registrations that were giving me trouble before, I have no objections and am a GO

**Comment by lbanner** [comment] 2015-06-23 03:21
Thanks @caileyfitz !!

**Closed** 2015-06-23 04:42 UTC
Labels: go/nogo
