### ISSUE TITLE
Missing activity logs

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#2873] opened 2015-05-28 17:38 UTC
I was sent links to two public projects, each of which had one file in them. 

You would expect the activity logs for these projects to have logs about the project being created and the file that was uploaded. 

However, the logs for both projects are completely empty (https://osf.io/hgbcn/; https://osf.io/hxiau/). Also, the 'last updated' date for one of the projects (https://osf.io/hxiau/) is 2013-10-24, but the file that was uploaded to the project was uploaded on 2013-12-11, so the dates are out of synch.

Example image:
![screenshot 2015-05-28 13 04 21](https://cloud.githubusercontent.com/assets/7332030/7866113/4161ba62-053b-11e5-83e7-682d04b4eb13.png)

**Comment by PatrickEGorman** [comment] 2015-05-28 20:03
This is definitely a weird error.  I thought at first it might be a time issue, but I see some recent activity logs that go back over a year.  I'm not sure what is happening here but I'll try to take a look at it.

**Comment by PatrickEGorman** [comment] 2015-05-28 20:09
Out of curiosity, would you or anybody else know of any other projects from 2013?  I wonder if this issue is dated.

**Comment by brianjgeiger** [comment] 2015-05-28 20:11
https://osf.io/ezcuj/ goes back to 2012 according to its logs.

**Comment by csoderberg** [comment] 2015-05-28 20:35
https://osf.io/ixgcd/ also goes back to august of 2013

On Thu, May 28, 2015 at 4:11 PM, Brian J. Geiger <notifications@github.com>
wrote:

> https://osf.io/ezcuj/ goes back to 2012 according to its logs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2873#issuecomment-106583189>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by PatrickEGorman** [comment] 2015-05-28 20:39
@brianjgeiger Page 128 of the project you posted doesn't appear to exist.  When one selects it, it stays on the current page and says there's no logs to show.

**Comment by csoderberg** [comment] 2015-05-28 20:41
That is really weird, because pages 127 and 129 both have logs that show up.

**Comment by brianjgeiger** [comment] 2015-05-28 20:48
So there are logs there, but there is a problem rendering them, I'm guessing.

**Comment by csoderberg** [comment] 2015-05-29 15:29
Here is a much newer project that is both just completely missing activity logs for a child component (https://osf.io/rtchq/), and missing the logs for some activities on the parent project (https://osf.io/b3k9a/) as well.

**Comment by chennan47** [comment] 2015-05-29 16:03
This fix for this problem is rdy, just need code review and merge.

**Comment by csoderberg** [comment] 2015-05-29 16:04
Great, thanks!

**Comment by sloria** [comment] 2015-06-11 17:34
Migration to fix the problem is currently running. The 2 affected projects mentioned by @csoderberg have been migrated. @csoderberg Can you verify?

**Comment by csoderberg** [comment] 2015-06-11 17:37
Looks like all the projects I mentioned now have logs. Thanks!

On Thu, Jun 11, 2015 at 1:34 PM, Steven Loria <notifications@github.com>
wrote:

> Migration to fix the problem is currently running. The 2 affected projects
> mentioned by @csoderberg <https://github.com/csoderberg> have been
> migrated. @csoderberg <https://github.com/csoderberg> Can you verify?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CenterForOpenScience/osf.io/issues/2873#issuecomment-111216176>
> .
>



-- 
Courtney Soderberg, Ph.D
Statistical and Methodological Consultant
Center for Open Science

**Comment by sloria** [comment] 2015-06-11 18:18
Excellent. Let me know if you see any further log-related problems.

**Closed by sloria** 2015-06-11 18:18 UTC
Labels: 5 - pending review, bug: production, priority - high
