### ISSUE TITLE
Email to merged account is addressed incorrectly to primary account's owner

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3346] opened 2015-06-26 13:54 UTC
### Steps
1. Go to [osf.io](http://www.osf.io).
2. Make sure you have access to two accounts, one of which you want to merge into the other
3. Make sure the accounts have different names (Jinlu Test vs. Pearson Creed)
4. Log into the primary account (the one you want to keep)
5. Go to Account Settings
6. Add the email address of the account you want to merge (pearsoncreed@gmail.com)
7. Check your email inbox
8. View the "Confirm account merge" email.

### Expected behavior
I expected that the email would be addressed to Pearson Creed, who is the owner of the merged account and the email address pearsoncreed@gmail.com

### Actual behavior
The "Confirm account merge" email is addressed to Jinlu Test.

![screen shot 2015-06-26 at 9 42 20 am](https://cloud.githubusercontent.com/assets/8591162/8378727/621c3984-1be9-11e5-8ef4-c9f08ac636a4.png)

**Comment by hmoco** [comment] 2015-06-26 14:15
@GaryKriebel I can work on this

**Comment by lbanner** [comment] 2015-06-26 17:04
@hmoco -- Please note @jinluyuan 's comment in PR #3348 .... right email is fixed, but one more needed change is correcting the addressee field. Thanks.

**Comment by hmoco** [comment] 2015-06-26 17:12
Yes, my fix actually does nothing, working on actually fixing the issue.

**Comment by hmoco** [comment] 2015-06-26 17:39
The issue is now (actually) fixed on #3354. Sorry about the confusion.

**Closed** 2015-06-26 17:43 UTC
Labels: 5 - pending review, bug: production, priority - medium
