### ISSUE TITLE
[Production & Staging] Project settings for read and read+write users nav widget jumps and changes size on scroll

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2683] opened 2015-05-08 15:07 UTC
## Steps
1. Go to a project you have read or read+write permissions on
2. Go to the project settings page
3. Scroll, making note of the left side navigation widget

## Expected
While scrolling, things would move smoothly on the page

## Actual
When scrolling, the left side navigation widget jumps and changes sizes during scrolling.
There is also an error in the console: "Uncaught Error: You cannot apply bindings multiple times to the same element."

![project settings 1](https://cloud.githubusercontent.com/assets/9381062/7539055/4ba88ec0-f572-11e4-9690-fdad70dc596c.gif)

**Comment by GaryKriebel** [comment] 2015-05-08 17:14
I am unable to recreate neither the action nor the error.

**Comment by sloria** [comment] 2015-05-08 17:25
@GaryKriebel are you able to recreate it when you have addons enabled? Looks like Nici has Box and S3 enabled in her screenshot

**Comment by GaryKriebel** [comment] 2015-05-08 17:32
I have all the addons enabled.... still don't see it

**Comment by GaryKriebel** [comment] 2015-05-08 17:35
![scroll](https://cloud.githubusercontent.com/assets/9437946/7541941/0ff8a8c8-f587-11e4-87e3-742f01487eee.gif)

**Comment by nicipfeiffer** [comment] 2015-05-08 17:46
@GaryKriebel you have to be a 'read' or 'read+write' contributor to have the issue

**Comment by GaryKriebel** [comment] 2015-05-08 18:03
Let me check that

**Comment by GaryKriebel** [comment] 2015-05-08 18:05
Mea Culpa.... it does exhibit the reported behavior as read+write.

**Comment by chennan47** [comment] 2015-05-18 20:06
@caileyfitz can you verify if this problem still exist? It doesn't happen to me.

**Comment by samanehsan** [comment] 2015-06-23 20:14
Closing this since it seems to no longer occur on production - neither I nor @caileyfitz can reproduce it.

**Comment by caileyfitz** [comment] 2015-07-30 19:32
@samanehsan @nicipfeiffer Am now seeing this on production, but it is NOT restricted to users with read + write or read-only access. 

Top of page: 
![screen shot 2015-07-30 at 3 29 27 pm](https://cloud.githubusercontent.com/assets/5975444/8992992/187f6768-36d0-11e5-9321-34af39eed11b.png)


After scrolling: 
![screen shot 2015-07-30 at 3 29 37 pm](https://cloud.githubusercontent.com/assets/5975444/8992996/1b66b242-36d0-11e5-89e7-e1c4c7a86385.png)


@GaryKriebel this may or may not be the same issue. Let me know if you want me to open a new issue for this.

**Comment by GaryKriebel** [comment] 2015-07-30 19:58
Let's just reopen this one.... they may all be related.

**Comment by nanchen47** [comment] 2015-08-13 14:21
Same issue as https://github.com/CenterForOpenScience/osf.io/issues/3972. Close this in favor of that one.

**Closed by nanchen47** 2015-08-13 14:21 UTC
Labels: 2 - ready, bug: production, bug: staging, intern, priority - low
