### ISSUE TITLE
[staging] [bug] Some tooltips in project view not working

### ISSUE THREAD

**Issue by kmjungersen** [CenterForOpenScience/osf.io#1451] opened 2015-01-07 17:31 UTC
This tooltip doesn't display on staging, and neither does the one for watching a project:

![screen shot 2015-01-07 at 12 26 14 pm](https://cloud.githubusercontent.com/assets/6546342/5649977/7c9f6440-9668-11e4-9624-4c5d52471031.png)

I tested in both Chrome and IE, and the problem only exists on staging.

**Comment by brianjgeiger** [comment] 2015-01-07 18:36
Duplicate of https://trello.com/c/GKeUl5eH (which you can't see, most likely). Staging-specific bugs are most likely being logged in trello boards right now to keep from overwhelming the github issues process. Best to check with @nicipfeiffer (and/or @caileyfitz when she's back next week) if you see something that's only on staging.

**Closed** 2015-01-07 18:37 UTC
