### ISSUE TITLE
[staging & production] Education and employment drag to reorder does not work for position 1

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1506] opened 2015-01-15 21:33 UTC
# Steps
1. Log in and go to the user settings page
2. Go to the employment or education tab
3. If you don't already have more than one position, create a new position
4. Drag position 2 above position 1
5. Attempt to drag position 1 below position 2
6. If you have more than two positions, try to drag position 2 below position 3

# Expected
Since all positions say *[drag to reorder]*, I assume that all positions are draggable and can thus be dragged above or below any other position to reorder. That is, I expect to be able to drag position 1 below position 2 to reorder.

# Actual
Dragging one position below another does not permit reordering. The position kind of just sits on top of the other (text overlaps) and then goes back to the original positions.

**Comment by huangginny** [comment] 2015-01-15 21:34
I'll take this issue, since I already have a fix for it....

**Comment by sloria** [comment] 2015-01-15 21:42
@huangginny This is a separate issue. The problem is that dragging the first item below subsequent items does not work (however, dragging other items works fine).

**Comment by leb2dg** [comment] 2015-05-22 14:04
I'm looking into this.

**Comment by lbanner** [comment] 2015-05-22 14:25
Thanks!

**Comment by samanehsan** [comment] 2015-06-10 18:17
Closing this issue since the fix has been merged in. :octocat:

**Closed by samanehsan** 2015-06-10 18:17 UTC
Labels: 2 - ready, bug: production, intern, priority - medium, ui
