### ISSUE TITLE
[Production & Staging] Intermittent Missing files/folders/components on grid on Project Overview and Files Tab

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2968] opened 2015-06-04 16:14 UTC
## Steps
1. Log in to osf.io
2. Go to the public project https://osf.io/4znzp/
3. Go to the project overview page and scroll through the files/folders/component list in the files widget
4. Check that you see all the components listed and files/folders
5. Go to the files tab
6. Check that you see all the components listed and files/folders
7. Try this with your own private projects that have lots of folders/add-ons/files listed; check that you see them in the grid

## Expected
I would expect that every time I go to see my files/folders/components for projects the grid would be populated and not blank

## Actual
Intermittently, there is blank grid.
![screenshot 2015-06-04 12 10 12](https://cloud.githubusercontent.com/assets/9381062/7988756/1a337412-0ab3-11e5-896a-68a2a4a83674.png)
![screenshot 2015-06-04 12 09 23](https://cloud.githubusercontent.com/assets/9381062/7988757/1e2e4bb4-0ab3-11e5-881a-36e5bad01074.png)
![screenshot 2015-06-04 12 05 07](https://cloud.githubusercontent.com/assets/9381062/7988764/246cfe8a-0ab3-11e5-9b6b-f4a866124300.png)

**Comment by caneruguz** [comment] 2015-06-04 16:17
This seems related to this problem: https://github.com/CenterForOpenScience/osf.io/issues/2845
Which has a proposed fix here: https://github.com/CenterForOpenScience/osf.io/issues/2845

I think it's likely to resolve this issue. If not we may need more information about what's going on.

**Comment by nicipfeiffer** [comment] 2015-06-04 16:19
@caneruguz They are likely related, however I am not expanding or collapsing folders to have the issue.  Simply going to page to view and grid is blank.

**Comment by caneruguz** [comment] 2015-06-04 16:21
Yes, the previous one was also not related to expanding, it was about total number of items in the view. 

Otherwise this bug report is very vague, the steps to repeat it should be working some time and not others, otherwise file browser would have been completely unusable. So then we need to know what is specific about this use case.

**Comment by nicipfeiffer** [comment] 2015-06-04 17:23
@caneruguz It seems like if the project is in the cache then it is all there, but if it has not been visited for some time then on the first visit the grid is blank.  If you continue to refresh repeatedly, eventually the grid will populate.  I guess that is what I mean by intermittent.

**Comment by caneruguz** [comment] 2015-06-05 13:34
I cleared my cache and I'm not seeing this behavior. We need to at least be able to repeat it.

**Comment by lyndsysimon** [comment] 2015-06-15 18:13
I've also been unable to reproduce this. If you can make it happen again, please attach a screenshot of the Javascript error console. The only thing I can think of is that there are requests that are/were failing to load before timing out.

**Comment by lbanner** [comment] 2015-06-15 18:45
I'm going to label "Defer" for now -- if only because I know it is intermittent / hared to intentionally replicate -- If issue arises, we'll capture as much error data as possible. Thanks.

**Comment by nanchen47** [comment] 2015-08-13 15:11
Can't repo this problem. Close this one for now. Please reopen it if it comes up again.

**Closed by nanchen47** 2015-08-13 15:11 UTC
Labels: 1 - deferred, bug: production, priority - high, ui
