### ISSUE TITLE
[Production]: Logs reflecting acitivity in Box add-on not rendering for some projects

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3277] opened 2015-06-23 15:35 UTC
## Steps 

1. Go to this project on production (ping me for access): https://osf.io/pm8re/ 
2. Check the project log
3. Click through the pages of the log until you see instances where the logs are not rendering (activity in Box add-on not rendering on June 8th)
4. Go to this project on the OSF (ping me for access): https://osf.io/5936d/
5. Check the project log
6. Click through the pages of the log until you see instances where the logs are not rendering (activity in Box add-on not rendering on June 8th)

## Expected behavior:

I expect that all logs will render and that each page of the log will contain unique logs.

## Actual behavior:

The logs that are supposed to reflect activity in the Box add-on do not render, and clicking through the different pages of the log for both projects displays the same broken log instances in the Box add-on from June 8th (which messes up the organization of the log by date; January and June logs are on the same page). Clicking through the pages of the log shows inconsistency (pages will reflect the same broken log instances over and over again). Users who used Box on this day may have similar log rendering issues, which makes it hard to have a sense for activity on projects as a whole. Perhaps the issue is also larger and occurred on more days that what I've found in my own projects on production.

## Screenshots

**First Project: https://osf.io/pm8re/**

**Page 2 of Log**

![lognotrendering](https://cloud.githubusercontent.com/assets/7093086/8309280/ae418476-1997-11e5-9db2-685db9189a41.png)

**Page 2 of Log (appears different now)**

![notrenderinglog](https://cloud.githubusercontent.com/assets/7093086/8309287/bdd32ea8-1997-11e5-98ae-fb6d605803b2.png)

**Second Project: https://osf.io/5936d/**

**Page 16 of Log**

![page16log](https://cloud.githubusercontent.com/assets/7093086/8309438/b404e94c-1998-11e5-88cb-1d78685b8c92.png)

**Page 17 of Log (same logs at bottom as 16)**

![boxbrokelog](https://cloud.githubusercontent.com/assets/7093086/8309446/bd3966be-1998-11e5-811a-fbe5f2c03d7f.png)

**Page 18 of Log (same logs at bottom as 16 and 17)**

![page18oflog](https://cloud.githubusercontent.com/assets/7093086/8309452/c3da7c56-1998-11e5-927d-3e6ffe624645.png)

**Comment by nanchen47** [comment] 2015-06-23 15:53
Duplicate issue as https://github.com/CenterForOpenScience/osf.io/issues/3230

**Comment by NatashaRichter** [comment] 2015-06-23 17:38
@nanchen47 Will the PR fix this issue too? I thought this issue was different from 3230 in that it's not "end of log behavior." The logs not rendering for this show up even at the beginning of logs; however, your pull request may fix this situation, as well.

**Comment by chennan47** [comment] 2015-06-23 17:40
@NatashaRichter Yes, it will, the error in log will prevent log after it
gets rendered. Fix the box log will fix the rendering problem.

**Comment by NatashaRichter** [comment] 2015-06-23 17:42
Thanks @nanchen47

**Comment by sloria** [comment] 2015-06-24 13:27
This isn't really a duplicate of #3230 ; the box logs may still be broken, pending merge of @chennan47's PR.

**Closed** 2015-06-24 14:03 UTC
