### ISSUE TITLE
[Staging & Production] SHARE: Graph index of providers does not equal total number of results

### ISSUE THREAD

**Issue by nicipfeiffer** [CenterForOpenScience/osf.io#2337] opened 2015-03-27 14:24 UTC
## Steps
1. Go to osf.io/share 
2. Enter ' * ' in to the search query so that all results for all providers are reported
3. Hover over the graph, go to the far right side.
4. Take note of the total number of events reported under the search bar

## Expected
The total number of events is equal to the total of each of the provider events for all results for all providers

## Actual
The numbers are not equal.

![ghpic](https://cloud.githubusercontent.com/assets/9381062/6869524/3d97f244-d46b-11e4-837c-3b99b6add3c0.jpg)
![screen shot 2015-03-27 at 9 52 11 am](https://cloud.githubusercontent.com/assets/9381062/6869533/4d0a8250-d46b-11e4-8cf6-0393385eba64.png)

**Comment by nanchen47** [comment] 2015-04-03 15:30
@nicipfeiffer Could you verify this problem still exists? I can't repo this problem.

**Comment by GaryKriebel** [comment] 2015-05-12 03:27
@nicipfeiffer will you check this?

**Comment by nicipfeiffer** [comment] 2015-05-12 12:52
@GaryKriebel I checked, but since the graph has been changed from the entire list of providers on hover to a single provider, I don't see the total number of events for each provider any longer.  Therefore, I can't calculate a total any longer.
![screenshot 2015-05-12 08 50 14](https://cloud.githubusercontent.com/assets/9381062/7587438/2eab793a-f884-11e4-9fcf-8d8b74b0c58b.png)

**Comment by GaryKriebel** [comment] 2015-05-12 13:23
Will close this issue and reopen if the issue is seen again.

**Closed by GaryKriebel** 2015-05-12 13:23 UTC
Labels: Bug: Production, discuss, Priority - High
