### ISSUE TITLE
[Safari] Side navbar in project settings shrinks and expands again upon scroll

### ISSUE THREAD

**Issue by NatashaRichter** [CenterForOpenScience/osf.io#3972] opened 2015-08-07 15:30 UTC
## Description

On Safari, at various screen sizes, when I scroll down on the Project settings page without adjusting page width, the side navbar shrinks and then grows larger again when I scroll up.

I've reproduced this when the screen is normal size and smaller size, but not consistently. However, it's been happening enough times for me that I thought it significant to report. See the screen video recording below for an example in real-time.

## Screen video recording

![navbar_shrinks_upon_scroll](https://cloud.githubusercontent.com/assets/7093086/9138783/02719642-3cf4-11e5-8dda-5416b1971bf5.gif)

**Comment by NatashaRichter** [comment] 2015-08-07 15:32
@caneruguz @haoyuchen1992 This is an interesting issue, which I've been seeing on Safari not consistently but often enough to be noticeable. Sorry that the gif isn't higher quality, but you can at least see the scroll issue.

**Comment by Johnetordoff** [comment] 2015-08-07 18:49
This should have been addressed in #3898, I don't know why it won't stick for safari, @nanchen47 could you assign me so I can take another look at it.

**Comment by caneruguz** [comment] 2015-08-10 13:32
@Johnetordoff it may be useful to check the function that does the resizing of that box to make sure it's not missing certain use cases.

**Comment by Johnetordoff** [comment] 2015-08-11 17:46
This is a tricky issue, because I know it happens sporadically, but I can't consistently reproduce it or see what might causing it programmatically. I know that clearing the browser cache fixes this problem temporarily (at least on firefox). I also know that this originally only happened when an Addon checkbox checked and applied, but I can't reproduce this on Safari, I am using the latest version Version 9.0 (10601.1.43), so it might be resolved.

**Comment by erinmayhood** [comment] 2015-08-24 18:10
@NatashaRichter can you see if this has been resolved and if so, close?

**Comment by NatashaRichter** [comment] 2015-08-25 12:55
Looks good now!

**Closed** 2015-08-25 12:56 UTC
Labels: bug: production, JIRA, priority - low, ui
