### ISSUE TITLE
[production] discrepancy between users in search and users in script

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2853] opened 2015-05-27 17:18 UTC
Doing a wildcard search for users (search "Category:User") does not return the same number of users the daily script (https://github.com/CenterForOpenScience/osf.io/blob/573d098d071eb8930225d88721e8f25d6b6014bc/scripts/analytics/benchmarks.py) does. 

Upon discussion with @fabianvf, criteria for user in search is: 
self.is_registered and
                self.password is not None and
                not self.is_merged and
                not self.is_disabled and
                self.is_confirmed()

which should be more restrictive than the script:
def get_active_users():
    return User.find(
        Q('is_registered', 'eq', True) &
        Q('password', 'ne', None) &
        Q('is_merged', 'ne', True) &
        Q('date_confirmed', 'ne', None)
    )

Yet number of users returned in search is greater than number returned on script. @fabianvf said he will discuss with @sloria

**Comment by brianjgeiger** [comment] 2015-05-27 17:22
My big concern is that is_confirmed and date_confirmed have traditionally caused us problems because they're both measuring the same thing in different ways, so it'll be easy for there to be a conflict in information.

**Comment by chennan47** [comment] 2015-05-28 13:39
The script need an update to put in Q('is_disabled', 'ne', True)

**Comment by lbanner** [comment] 2015-05-28 13:42
@chennan47 @brianjgeiger ... possible intern task?

**Comment by chennan47** [comment] 2015-05-28 13:44
@lbanner if the querry is the only thing make the scirpt return different number from elastic, this is an easy fix. Otherwise, needs to look into the production database to figure out the reason to cause the difference.

**Comment by brianjgeiger** [comment] 2015-05-28 13:44
That won't make the script show more users, though, so there's more going on. If that were the contributing factor, then the script would have more users than the search, as Sara suggested.

How many users do we have where date_confirmed isn't None but is_confirmed is true? At this point, we shouldn't have any of those, because those cause login problems and the like. We need to find the answer to that question and fix it. 

In the end, both of those queries should use the same information, but that's a minor issue. The big one is why they are different and what problems we don't see because of it.

**Comment by saradbowman** [comment] 2015-05-28 13:45
I agree the script needs an update to include the disabled piece, what I
find more concerning is that the search index returns a value higher than
the script, despite excluding disabled accounts. I'm interested to know if
this is because of the date_confirmed / is_confirmed issue @bgeiger raises.
I think we need to determine which is the most appropriate value there as
well.

**Comment by chennan47** [comment] 2015-05-28 13:50
@lbanner I will take a look at this.

**Comment by lbanner** [comment] 2015-05-28 13:51
OK @chennan47

**Comment by lbanner** [comment] 2015-07-21 15:13
FYI: I am closing this issue now as it generally was met by #2883 However, questions of consistency in count remain, so we're  keeping it on radar. Thanks.

**Closed by lbanner** 2015-07-21 15:13 UTC
Labels: 5 - pending review, discuss, enhancement
