### ISSUE TITLE
[staging & production] Creating access token for Box gives 403 Forbidden

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2521] opened 2015-04-17 15:55 UTC
**This only happens for *some* projects... not sure the distinguishing features that cause this to fail**

# Steps
1. Go to user settings and delete the access token for Box
2. Go to a project on staging where you have admin access
3. Enable Box
4. Click to create an access token
5. Go through the steps to allow OSF access 
6. Press 'Grant access to Box' to authorize OSF access to Box

# Expected
I expect that going through these steps would enable and connect Box to a project.

# Actual
The user is faced with a 403 error displayed as JSON: 
![screen shot 2015-04-17 at 11 39 55 am](https://cloud.githubusercontent.com/assets/5975444/7205584/5e9f1ba0-e4f8-11e4-91fd-6664fbf85dcd.png)

More info:
![screen shot 2015-04-17 at 11 40 03 am](https://cloud.githubusercontent.com/assets/5975444/7205587/6011bdc6-e4f8-11e4-8aac-6b0a82b93161.png)

In the very least, the error should be handled and not be displayed as JSON, even if we cannot identify the problem at this point.

**Comment by lbanner** [comment] 2015-04-18 02:36
Given the inconsistency -- is it possible this is an error coming out of BOX? or the BOX connection?

**Comment by chrisseto** [comment] 2015-04-21 15:33
@caileyfitz This may be fixed, Box was having API issues when this issue was created.
https://status.box.com/ shows everything as all green.

**Comment by lbanner** [comment] 2015-04-21 15:46
I'm going to close for now. Thanks.

**Comment by GaryKriebel** [comment] 2015-05-13 17:59
Looks like @lbanner clicked "comment" and not "Close and comment".

I'm closing and commenting AND tagging name to make sure he gets another email while he's sitting on a beach.

**Comment by caileyfitz** [comment] 2015-07-06 13:54
@lbanner I'm not crazy!!!

**Comment by lbanner** [comment] 2015-07-06 13:58
Reopening! @icereval or @chrisseto ? Thanks!

**Comment by mfraezz** [comment] 2015-07-08 14:32
Couldn't reproduce this. @caileyfitz could you add me to a project on staging where this is an issue? Staging id is fh5em.

Also, this might be closed by https://github.com/CenterForOpenScience/osf.io/pull/2195 , depending on what's going wrong

**Comment by caileyfitz** [comment] 2015-07-08 15:39
@mfraezz project id is https://osf.io/b9v2w/

**Comment by mfraezz** [comment] 2015-07-08 16:32
Ah. I got this to happen once. @lbanner can confirm, she's not crazy. 

It looks like it's due to the `state` parameter, though I'm not sure why. (It's normally used to verify that a user's data wasn't modified during transmission: a state is generated by the OSF before authorization, passed to Box during auth, and that same one is returned to the OSF by Box.) For it to fail seemingly nondeterministically, it would have to be either different upon being returned by Box or lost by the OSF while the user is authorizing, and neither one of those should be happening. There may be some asynchronicity at play that I don't know about, though.

**Comment by lbanner** [comment] 2015-07-08 16:40
That's good to confirm about @caileyfitz, @mfraezz ! Are you on this one then? Thanks.

**Comment by mfraezz** [comment] 2015-07-08 17:21
It's low priority and *may* be fixed by my [PR](https://github.com/CenterForOpenScience/osf.io/pull/2195) (scheduled for 0.43). If it's still present after that gets merged I'll work on it

**Comment by lbanner** [comment] 2015-07-08 17:24
Got it - TY

**Closed** 2016-03-08 21:34 UTC
Labels: 5 - pending review, bug: production, priority - low
