### ISSUE TITLE
[production bug]  Add unregistered contributor freezes and does nothing

### ISSUE THREAD

**Issue by bnosek** [CenterForOpenScience/osf.io#2317] opened 2015-03-25 20:45 UTC
Clicking on add here generating no response:

![screen shot 2015-03-25 at 4 43 56 pm](https://cloud.githubusercontent.com/assets/1761504/6835017/44a501b6-d30e-11e4-8bac-609810ec4ce7.png)

**Comment by bnosek** [comment] 2015-03-25 20:46
I did it again and it worked.  The time it failed, I had added added another contributor that was in the system, and then tried to add Kirstie before confirming adding that first contributor.  The second time, I added the unregistered contributor first and did not have a problem.  I have a few more to add and will try different combinations.

**Comment by lbanner** [comment] 2015-03-25 20:49
@nicipfeiffer or @caileyfitz -- if you can, maybe double check / see if you can replicate this one? TY

**Comment by bnosek** [comment] 2015-03-25 20:49
Tried it again the first way and had the same problem:

[1] find an existing contributor and put in queue to add to project
[2] search for an unregistered contributor
[3] add unregistered contributor 

Freezes at the attempt to add the unregistered contributor

**Comment by huangginny** [comment] 2015-03-25 20:52
I remember fixing this problem before, but it never gets merged
https://github.com/CenterForOpenScience/osf/pull/1109

**Comment by lbanner** [comment] 2015-03-25 20:53
Good @huangginny -- will followup. TY

**Comment by nicipfeiffer** [comment] 2015-03-26 00:56
@lbanner I was unable to replicate follow the steps @bnosek gave above, but will get more details in the morning and try again.

**Comment by lbanner** [comment] 2015-03-26 02:06
OK - thank you - looks like @huangginny had an earlier fix on this - she is updating the PR.

**Comment by huangginny** [comment] 2015-03-26 13:36
@nicipfeiffer To reproduce the bug you need to 

1. Put a name in the search bar of the add contributor modal
2. Click search
3. Add someone from the search results
4. What @bnosek said

If you add your first contributor directly from "my recent/frequent collaborators" you won't reproduce it

**Comment by caileyfitz** [comment] 2015-03-26 14:34
I was able to reproduce this with the steps that @huangginny listed.

**Comment by nicipfeiffer** [comment] 2015-03-26 14:45
Thanks @huangginny I am now getting the error

**Closed** 2015-03-26 14:52 UTC
Labels: Bug: Production, discuss
