### ISSUE TITLE
[production] GDrive doesn't display folders named with cyrillic alphabet

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#2610] opened 2015-04-30 13:46 UTC
User reports he is unable to authorize an individual folder for his Google Drive account. In add-on, only 'full drive' option is shown, with the 'syncing' symbol (which never goes away): 

![screen shot 2015-04-30 at 9 42 09 am](https://cloud.githubusercontent.com/assets/7749914/7413927/5c4f0048-ef1d-11e4-918d-164f02b659d2.png)

Removing and then adding google drive back to the project does not solve the problem, nor does deleting the access token and creating a new one. 

User is on Windows NT: 6.1 SP1, with Chrome 42.0.2311.90 m, but also experiences issue on IE. 

I cannot recreate the issue on my end in Chrome or Safari (OS X 10.9.5)

**Comment by lbanner** [comment] 2015-04-30 23:43
Saw this discussion on OSF Dev flow .... any resolution?

**Comment by saradbowman** [comment] 2015-04-30 23:53
So far no one can replicate the error.

**Comment by lbanner** [comment] 2015-04-30 23:54
The user still experiencing it? Tried the ol' log-off account, restart your machine, log back on and connect the add-on again approach? :smiling_imp:

**Comment by saradbowman** [comment] 2015-05-01 00:53
this was the case yesterday, but I will confirm.

**Comment by GaryKriebel** [comment] 2015-05-08 14:55
Since we are unable to reproduce, we will close this and reopen if more issues surface.

**Comment by saradbowman** [comment] 2015-06-05 13:27
A second report on the help desk, and user diagnosed the issue. In this second case, only certain folders would not expand (did not affect the entire drive):

The folders which don't expand (+) contain subfolders with cyrillic
names in it. To test this I've created three new folders on my GDrive with
different subfolders (folders at first level, subfolders - at second):

- Trial folder 1
- New folder
- Trial folder 2
- Новая папка # that means "New folder" in russian
- Trial folder 3
- New folder
- Новая папка

Trial folder 1 expanded without any problems, Trial folders 2 and 3 did not
(screenshoots below).

![screen shot 2015-06-05 at 9 21 54 am](https://cloud.githubusercontent.com/assets/7749914/8006811/0a8264ee-0b65-11e5-82fc-824098c63ce6.png)

![screen shot 2015-06-05 at 9 22 11 am](https://cloud.githubusercontent.com/assets/7749914/8006815/0f83abe2-0b65-11e5-9292-27bccfe771b6.png)


Also, after I've created folder with the name "Новая папка" right in the
root of my disk it stopped expand (+) at all.

**Comment by GaryKriebel** [comment] 2015-06-05 13:35
@saradbowman is checking with the first user to confirm these are similar issues.

**Comment by saradbowman** [comment] 2015-06-08 12:25
First user has folders with Hebrew characters, so the issues are related.

**Comment by chrisseto** [comment] 2015-06-08 12:34
@saradbowman This should be fixed as of last night, would you mind checking?

**Comment by saradbowman** [comment] 2015-06-08 12:38
@chrisseto it is! y'all are fast! Thanks. I'll update the users who reported the bug.

**Comment by saradbowman** [comment] 2015-06-12 15:42
This issue is fixed now, but user reports that there are unrecognized characters in one of the folder names. Folder name: 2015 РФФИ а Маркеры ошибок

Displays as: 

![screen shot 2015-06-11 at 8 39 31 am](https://cloud.githubusercontent.com/assets/7749914/8133720/fbd2abaa-10f7-11e5-9dfa-2657687adca7.png)

**Comment by nanchen47** [comment] 2015-07-26 18:26
The pr has been merged and deployed on production.

**Closed by nanchen47** 2015-07-26 18:26 UTC
Labels: 5 - pending review, bug: production, community, priority - high
