### ISSUE TITLE
Deleting a contributor gives false impression

### ISSUE THREAD

**Issue by brianjgeiger** [CenterForOpenScience/osf.io#2312] opened 2015-03-25 17:22 UTC
Steps
-------
1. Go to the sharing tab of a project with many contributors that you administer
2. Click x to remove a contributor near the top of the list
3. See that it says that the user is deleted

Expected
------------
The user is deleted.

Actual
--------
The user will be deleted pending the save. The save button is waaaay down at the bottom of the screen, so if there are too many contributors, then you won't see it.

Suggested fix
-------------------
Change the wording to "Delete after save" and have it link to an anchor that is at the save button. That way, if they click the "Delete after save" link, they will be taken to the save button.

**Comment by cosenal** [comment] 2015-03-27 20:03
Why not deleting the contributor directly in the first place? And

**Comment by lbanner** [comment] 2015-03-27 20:07
:+1: @cosenal -- and I appreciate you sharing that article!

**Comment by brianjgeiger** [comment] 2015-03-27 20:14
That is definitely where we are headed, but it would require a significant re-write of the code. Because this is such a potential problem (though I see it's tagged as low priority right now, so there may be some disagreement there), we wanted a quick fix to keep people from thinking they had removed a contributor but hadn't. Ultimately, all actions that happen on that screen will happen immediately.

**Comment by lbanner** [comment] 2015-03-27 20:17
"Low" as it is an improvement, but not a bug -- With that said, if there are reported user issues + mistakes + complaints around this potential confusion currently, then I'll certainly up it!

**Comment by brianjgeiger** [comment] 2015-03-27 20:21
Not reported from users, but very likely that someone could be left with access to a project when they shouldn't. Consequences could be very bad.

**Comment by lbanner** [comment] 2015-03-27 20:22
Word - TY

**Comment by chennan47** [comment] 2015-03-31 15:48
@lbanner @brianjgeiger It's a simple change for the language part. However the redirect link will conflict with the current behavior of the contributor table. So if currently you click a second time anywhere on the removed contributor lane, it will unremove the contributor. Thoughts?

**Comment by lbanner** [comment] 2015-03-31 15:51
Good one for you to grab @chennan47 -- @brianjgeiger Look to you for thoughts here? TY

**Comment by chennan47** [comment] 2015-04-01 16:57
A short hotfix for this is rdy. 
Since there is binding to the panel that when a contributor is in the deletedStages, the second click on anywhere of the line will just revert the remove contributor behavior. Add a redirect link to the save button on the line won't work under current behavior. And add another button outside the contributors table create a lot of extra css problems which takes time and  is not in the priority.

**Comment by sloria** [comment] 2015-04-07 13:29
@chennan47 Changed the language to say "Will be removed after Save". @brianjgeiger Is this change enough to close the issue?

**Comment by brianjgeiger** [comment] 2015-04-07 13:37
Yes, that should work.

**Comment by nanchen47** [comment] 2015-04-07 14:31
The pr has already been merged and go on production.

**Closed by nanchen47** 2015-04-07 14:31 UTC
Labels: 5 - Pending Review, Bug: Production, enhancement, Priority - High
