### ISSUE TITLE
[staging & production] Clicking Figshare/Dataverse file yields Unable to resolve error until refresh

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#1491] opened 2015-01-14 21:01 UTC
Related to #1370 but this issue extends it to Dataverse and files that have not just been uploaded.

# Steps
1. Go to a project where Figshare/Dataverse is enabled
2. Upload a new file to to the Figshare/Dataverse add-on via the files tab
3. After upload, click the file.
4. Refresh the page.
5. Return to files page and click another Figshare/Dataverse file (if another exists)

# Expected
I expect that clicking a Figshare/Dataverse file would redirect to a page where the file is rendered immediately.

# Actual
Clicking a file name (that hasn't been clicked for a few minutes -- unsure of the specific limits here) redirects to a page that displays an Unable to resolve error. Upon refreshing the page, however, the file is correctly rendered. Seems to have something to do with timing of possibly getting the file from Figshare/Dataverse?

**Comment by nanchen47** [comment] 2015-04-03 21:26
@chrisseto has a fix for figshare part of this problem. Defer to check after April 13th dataverse update or the dataverse part.

**Comment by rliebz** [comment] 2015-04-21 13:24
I have been unable to reproduce this issue with Dataverse 4.0 now on Waterbutler.

**Comment by chrisseto** [comment] 2015-04-21 13:25
@caileyfitz This should be resolved now, can you double check?

**Comment by caileyfitz** [comment] 2015-04-21 13:37
Not seeing this problem anymore :whale:

**Comment by chrisseto** [comment] 2015-04-21 13:40
@nanchen47 Would you mind closing this?

**Comment by lbanner** [comment] 2015-04-21 15:58
Got it -- Closed! TY

**Closed by lbanner** 2015-04-21 15:58 UTC
Labels: 1 - Deferred, Bug: Production, Priority - Low
