### ISSUE TITLE
Chrome Incognito window Add Contributors

### ISSUE THREAD

**Issue by Ghalko** [CenterForOpenScience/osf.io#1867] opened 2015-02-23 19:57 UTC
Pop-up shows all elements.

## Steps
1. Open Chrome incognito window.
2. Go to an OSF project either staging or production
3. Go to Sharing.
4. Click "Add" next to Contributors

## Expected

Normal pop-up.

## Actual

![screen shot 2015-02-23 at 2 26 50 pm](https://cloud.githubusercontent.com/assets/5169088/6335741/99a80aba-bb6b-11e4-8bc4-2ff31615efe3.png)

This may not be supported, but it might point at an underlying issue.

**Comment by brianjgeiger** [comment] 2015-02-23 20:03
This is an indication that something is breaking the Knockout ViewModel. There should be a Javascript error. Could you grab that and add it? It definitely should not happen.

**Comment by Ghalko** [comment] 2015-02-23 20:17
With a second try it seems to work fine. I will try to reproduce this, thank goodness for image evidence!

**Comment by Ghalko** [comment] 2015-02-23 20:25
- Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError
- Failed to create temp file 2 : It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources.

Managed to recreate in first time use of incognito window.

**Comment by chennan47** [comment] 2015-02-24 15:25
Can't repo this problem. Tried that on chrome incognito window both on staging and production. Everything is fine. @Ghalko can you verify the problem still exist?
![screen shot 2015-02-24 at 10 23 12 am](https://cloud.githubusercontent.com/assets/4974056/6352269/65194878-bc0f-11e4-9e11-56bd5b0f844f.png)
![screen shot 2015-02-24 at 10 25 47 am](https://cloud.githubusercontent.com/assets/4974056/6352290/8461965e-bc0f-11e4-80d0-8fc32b40e7b2.png)

**Comment by Ghalko** [comment] 2015-02-24 16:52
One of the problems is that this only happens the first time Incognito is used for OSF. So if you have been there before then you won't get the bug despite incognito saying that it saves nothing. After failing to reproduce it on the Mac, I tried my PC and got the information written in my previous reply and re-opening of this issue.

**Comment by huangginny** [comment] 2015-03-04 19:35
I see this coming up once in a while too... haven't figured out when it happens

**Comment by brianjgeiger** [comment] 2015-03-11 21:01
This doesn't make much sense. There are a few instances of these errors in Google's search index, but we shouldn't be doing anything with files at all. Can you try to log all of your network requests or js calls etc and maybe see if there's a difference between something that happen in incognito vs in normal, or even two different incognito requests, one that succeeds and one that fails? 

To be sure, there should be some differences just because you're getting a lot more data transferred properly in one case vs another. But there may be something else.

**Comment by chennan47** [comment] 2015-03-11 21:07
I was able to repo this problem once a while ago. It only happens the first
time when you open a incognito window. After one refresh, this problem is
gone forever. It can be some broswer cache problem with the mako files and
knockout binding. But haven't seen this problem recently after 0.27. I
don't really think this is a big problem since it doesn't affect user's
project or any data and is gone forever after one refresh. And it's hard to
repo and debug. Might just close this one.

**Comment by brianjgeiger** [comment] 2015-03-11 21:11
The errors reported above will happen independently of the bug; I get them but don't have a problem with adding contributors. 

It's not a bug that's likely to happen frequently, and it's not a harmful problem, but it's a terrible interface glitch. Maybe worth deferring, and maybe future changes will fix the problem or otherwise make it go away, but I don't think I'm for closing it until then.

**Comment by lbanner** [comment] 2015-03-12 13:56
OK -- deferring this one -- Thanks

**Comment by nanchen47** [comment] 2015-08-13 07:39
This problem doesn't happen anymore. Close for now, reopen it if it happens.

**Closed by nanchen47** 2015-08-13 07:39 UTC
Labels: 1 - deferred, bug: production, priority - low
