### ISSUE TITLE
[staging] [add-ons] Order of appearance

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#896] opened 2014-09-05 18:34 UTC
This is more of an organization issue and not a functional one. Is there a reason add-ons are in a random order for manual configuration? I think it would make sense for the add-ons to appear in the same order as they do when a user is enabling them. If not that, I think that add-ons in different categories should not be intermixed (storage vs security). For example, here is the configuration view for enabling:
![screen shot 2014-09-05 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/5975444/4169741/b04f0164-352a-11e4-8e06-62ed45b8cbe7.png)
But after add-ons are enabled, their order is mixed up: 
![screen shot 2014-09-05 at 2 27 39 pm](https://cloud.githubusercontent.com/assets/5975444/4169744/bbac9e5e-352a-11e4-88b9-3633a40f0b43.png)
The order is
GitHub
Two-factor
Amazon S3
FigShare
Dataverse
Dropbox 
as opposed to the order listed in the first window

**Comment by caileyfitz** [comment] 2015-03-16 19:02
Tagging @samanehsan here. 

# Steps
1. Go to project settings
2. Enable all add-ons and press Submit

# Expected
I expect that the add-ons would be listed in alphabetical order in both the enable view and the configuration view. 

# Actual
When figshare got changed to be all lowercase, it also dropped below the other add-ons in the list that displays in the enabling view. See below: 
![screen shot 2015-03-16 at 2 55 08 pm](https://cloud.githubusercontent.com/assets/5975444/6673872/79ac98b6-cbec-11e4-98ce-245719f10f8c.png)

figshare is also now located at the bottom of the configuration view. I think this may have to do with the sorting being case-sensitive. I know @jmcarp encountered something similar when sorting files alphabetically.

**Comment by lbanner** [comment] 2015-03-16 19:43
Didn't we take care of this one?

**Comment by brianjgeiger** [comment] 2015-03-16 19:50
This regression is likely because the sort comparator is case sensitive. Depending on how it's happening, ensuring that the sort happens in a case-insensitive way should fix the problem. This could be by comparing everything as all lower-cased or all upper-cased, or perhaps by passing a parameter to the sorter to ensure that it does not consider case.

The downside of converting to upper/lower case is that it will likely break on unicode characters. Not a problem now, but if we ever try to integrate :horse:.horse or some similar unicode-named service, we may run into problems. That would likely not be the first place we have that trouble, though.

**Comment by caileyfitz** [comment] 2015-03-16 19:50
@lbanner We did, but lowercasing figshare (occurred very recently) bumped it to the bottom of the list, presumably because of case sensitivity in alphabetic sorting.

**Comment by samchrisinger** [comment] 2015-03-16 19:52
I implemented the fix for this last time around, and sorting by name feels pretty brittle. We should consider defining this somewhere in a settings file.

**Comment by brianjgeiger** [comment] 2015-03-16 19:55
It's not super-brittle, and it happens in other places where we have to sort things. Maintaining a list is problematic because what happens if you leave an item off the list? It's trouble to maintain a separate piece of information if we don't have to.

**Comment by lbanner** [comment] 2015-03-16 19:58
I'll go with that -- can we simply sort and ignore case?

**Comment by lyndsysimon** [comment] 2015-06-16 18:34
"figshare" - regardless of capitalization - shouldn't be at the bottom of the list...

**Closed** 2015-06-19 18:00 UTC
Labels: 5 - pending review, bug: production, intern, ui
