### ISSUE TITLE
[staging & production] File Version List scroll bar does not persist

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2676] opened 2015-05-08 14:33 UTC
Reported by @nicipfeiffer on the 0.35 Trello board:

## Steps
1. Log in to staging
2. Go to a project you have admin privileges on
3. Upload >10 versions of a file to a project's osf storage
4. Click on a file to go to the file detail page
5. Scroll the version table

## Expected
The fact that the version table scrolls should be obvious like the file tree, files grid and project dashboard.  All have a scroll bar that persists, meaning it stays darkened on the page even when not in use to make it apparent to the user that it's available for use.  I would expect consistent scroll bars throughout the site.

## Actual
The scroll bar is not obvious, only if you have the mouse in that section and scroll with it do you realize that it is there.  Also, the last file version in the list is cut off.

![uu](https://trello-attachments.s3.amazonaws.com/5542d7d3de1417cfb38ed8e6/600x271/9302d47dda9d4f765eef9febbb47b8e4/Screenshot_2015-04-30_21.32.21.png)

**Comment by GaryKriebel** [comment] 2015-05-08 16:58
This was fixed in https://github.com/CenterForOpenScience/osf.io/pull/2657

**Closed by GaryKriebel** 2015-05-08 16:58 UTC

**Comment by caileyfitz** [comment] 2015-05-08 17:22
@nicipfeiffer and I are still seeing the problem, even though @GaryKriebel cannot reproduce it.

**Comment by GaryKriebel** [comment] 2015-05-08 17:25
can't reproduce

3 different browsers:
![screen shot 2015-05-08 at 1 11 39 pm](https://cloud.githubusercontent.com/assets/9437946/7541749/93f1bc84-f585-11e4-8962-0a69844063f5.png)
![screen shot 2015-05-08 at 1 12 58 pm](https://cloud.githubusercontent.com/assets/9437946/7541752/962b40e2-f585-11e4-8e78-e77ede4c2d5f.png)
![screen shot 2015-05-08 at 1 13 29 pm](https://cloud.githubusercontent.com/assets/9437946/7541755/99e3ca42-f585-11e4-8e16-8f5cf9a1a8c4.png)

**Comment by caileyfitz** [comment] 2015-05-08 17:25
![screen shot 2015-05-08 at 1 25 36 pm](https://cloud.githubusercontent.com/assets/5975444/7541776/bf3b1a02-f585-11e4-8984-4f9441fbfef4.png)

**Comment by sloria** [comment] 2015-05-08 17:29
This looks to be an OS-specific--not browser-specific problem. Some versions/configurations of Mac have persistent scroll bars; others do not.

**Comment by brianjgeiger** [comment] 2015-05-08 17:31
You can set it in your system preferences.

![screen shot 2015-05-08 at 1 31 42 pm](https://cloud.githubusercontent.com/assets/6599111/7541889/95e1a6ac-f586-11e4-96cc-2d4231a022f4.png)

**Comment by caileyfitz** [comment] 2015-05-08 17:37
Ah, thanks for the insight @sloria and @brianjgeiger!

**Comment by nicipfeiffer** [comment] 2015-05-08 17:40
Ah ha!  Now it looks good.
