### ISSUE TITLE
No warning that uploading file of same name replaces original file

### ISSUE THREAD

**Issue by jinluyuan** [CenterForOpenScience/osf.io#3412] opened 2015-07-01 18:52 UTC
### Steps
1. Go to osf.io
2. Go to one of your projects
3. Upload a file into any storage add-on
4. Edit the file on your computer, without renaming the file
5. Upload the file again

### Expected behavior
I expected that the files widget would either 1) warn me that my new file would replace the old one or 2) add a "_1" into the name of the new file in order to preserve the original file.

### Actual behavior
No warning message appears, and my original file is replaced.

**During upload**
![screen shot 2015-07-01 at 2 50 41 pm](https://cloud.githubusercontent.com/assets/8591162/8462257/8f89ecd4-2000-11e5-9818-939fa877ed6f.png)

**After upload**
![screen shot 2015-07-01 at 2 50 57 pm](https://cloud.githubusercontent.com/assets/8591162/8462287/b64f6e20-2000-11e5-946c-8a0d94eed8ff.png)

**Comment by hmoco** [comment] 2015-07-14 16:00
At least for OSF Storage, this does replace the file as the latest version. However, the earlier versions are still available under the revisions tab on the file view page, so in that sense the new file is test_1 or test_2, except test_0 is only available under the file view page.

**Comment by jinluyuan** [comment] 2015-07-14 16:11
@hmoco I think the behavior is fine, but it would be preferable to have a warning message. Users might not even realize that the different versions are available to view in the OSF. When a user clicks to view a file, the Revisions pane isn't open by default, so it's not noticeable unless the user knows where to look.

**Comment by hmoco** [comment] 2015-07-14 17:12
I agree, I just wanted to clarify that the files are not just gone without warning. A message saying something like 
## file_name will be replaced
### However, it will still be available under the revisions tab when viewing the new file

**Comment by lbanner** [comment] 2015-07-14 17:18
@jlcohoon Please, see above ^^ for appropriateness of language. Thoughts?

**Comment by jinluyuan** [comment] 2015-07-14 17:32
Suggestion:

### This will replace the existing version of file_name
Previous versions are preserved in the file viewer's Revisions pane.
[Cancel][Confirm]

**Comment by hmoco** [comment] 2015-07-14 17:33
Oh, that was just an example, I'm not currently working on this. I can however.

**Comment by jinluyuan** [comment] 2015-07-14 17:34
@hmoco It's cool! I just want it to be as clear as possible.

**Comment by jlcohoon** [comment] 2015-07-14 17:42
Can we include a "don't ask this again" option if we give a warning like that?

**Comment by lbanner** [comment] 2015-07-14 17:50
Cool option if possible, especially if you think you want to include the [cancel][confirm].

**Comment by jlcohoon** [comment] 2015-07-14 17:58
I personally think that it is unnecessary to include the alert. I do think it would surface the version control feature more, so that would be good, but it would introduce an extra hurdle for users. In all likelihood, if you wanted an extra "_1" or something added to the end to create a second copy, you would do so yourself when you saved the file on your computer. Not providing a warning and automatically replacing the file is consistent with how other services do this (see Dropbox).

If we can add the option to permanently dismiss the warning, I think it's okay to include, but otherwise I'd vote no.

**Comment by hmoco** [comment] 2015-07-14 18:08
I am unsure of how this feature could be done. Not saying it is not possible, but it will be a lot harder then simply adding the warning (which is already included for when you rename the file).
![screen shot 2015-07-14 at 2 03 29 pm](https://cloud.githubusercontent.com/assets/6268982/8680735/4dd9c0f8-2a31-11e5-9164-e4cb8a55cfce.png)
Specially if the dismissal of the warning is permanent, meaning it would need to be attached to the profile settings. Again, I believe it can be done but may not be worth the effort (or worth adding more options to the settings page if that is the route taken, since after dismissing the warning, a user should be able to enable them again)
But then again, as @jinluyuan mentioned, the user would need to be familiar with the osf to realize that the earlier version would end up in the revisions tab (and to know how to get there)

**Comment by jinluyuan** [comment] 2015-07-14 18:11
This discussion has led me to discover that uploading the same name file into Dataverse produces a -1 at the end of the file, and for figshare, the same file is just displayed twice. All other add-ons and OSF Storage replace the existing file.

![screen shot 2015-07-14 at 2 04 16 pm](https://cloud.githubusercontent.com/assets/8591162/8680815/e18adb84-2a31-11e5-8d75-8db85b428cc2.png)
![screen shot 2015-07-14 at 2 06 46 pm](https://cloud.githubusercontent.com/assets/8591162/8680816/e18d432e-2a31-11e5-8081-c91cf28dbef1.png)

That issue aside, I like Henrique's modal. Although it would be an extra step, it's not too often that a user uploads the same name file, and if he does, it's an extra precaution that's worth taking. I like the fact that my computer's Finder prompts me every time about it.

![screen shot 2015-07-14 at 2 01 12 pm](https://cloud.githubusercontent.com/assets/8591162/8680852/2189409a-2a32-11e5-8a43-d60e88197bf8.png)

**Comment by hmoco** [comment] 2015-07-14 18:12
Actually that modal is Caner's work. If you select keep both, it renames it to test(1).txt

**Comment by lbanner** [comment] 2015-07-14 18:13
Yeah. I am in favor of the warning in general, especially as we use it in moving/copying. Consistency. @hmoco Can we simply apply @caneruguz 's modal?

**Comment by jinluyuan** [comment] 2015-07-14 18:13
@hmoco Oh alright, props to Caner. Any way we could then change Dataverse's versioning to be test(1).txt as well, instead of the existing test-1.txt? Or vice versa, as long as we maintain consistency.

**Comment by hmoco** [comment] 2015-07-14 18:23
@lbanner we can use it, but it will be a little more difficult if we want to retain the rename function.

**Comment by jlcohoon** [comment] 2015-07-14 18:24
If we add this modal everyone will say keep both without realizing that
that means they'll have two files rather than two versions. I really think
that this will be discouraging the use of version control.

**Comment by hmoco** [comment] 2015-07-14 18:33
How about no keep both button? It's either cancel or create new version or something like that. 
I guess the question is, how many users are aware of version control and would be annoyed by the modal popping up all the time when they really just want to create a new version and how many users just are not aware of it and would benefit from the modal. Now that I think about it, being it that version control is the intended behavior, and that naming two files the same thing is something that people would hopefully not do (unless they want to create a new version), the modal hurts intended behavior while only being useful when the user is not being careful with their naming practices.

**Comment by brianjgeiger** [comment] 2015-07-14 18:37
If it becomes a source of confusion for users, we might be able to put some more UI effects to make it more clear what is happening. It'll be trickier with multi-file drag and drop, but doable.

**Comment by jinluyuan** [comment] 2015-07-14 18:38
The case I'm considering -- If I have two files both named "data.txt", perhaps in different folders in my computer, I would not want the first one to be replaced by the second, even if there is versioning in the file viewer, because they could be two completely different, unrelated files. 
I feel like it's best to have the warning, with just a [Cancel][Confirm] (or some other word) as the options. 

As a side note, this was brought up as an issue by our third-party testing service, and as they are similar our users, who do not have as much OSF knowledge as us, I thought it was significant that they found this confusing.

**Comment by hmoco** [comment] 2015-07-14 18:41
I guess the idea is that if we are promoting users to make use of version control, we should not be saying they might be making a mistake when they are trying to use the feature. I think if there was a way to separate the two behaviors (accidental name vs. new version) that would be ideal

**Comment by hmoco** [comment] 2015-07-14 18:42
With that in mind, is there a way currently (maybe a button) that does something to the effect of "upload new version"?

**Comment by jlcohoon** [comment] 2015-07-14 18:44
I think the scenario is an unlikely one and still disagree about the necessity of the warning. It seems like you're punishing people who use the feature by giving them an extra step. So, I still disagree, but if we have to have a warning then it shouldn't say "replace." It should say, "Are you sure you would like to create an additional version of the file XXXX?" with Cancel and Create New Version as the buttons.

**Comment by brianjgeiger** [comment] 2015-07-14 18:46
My expectation is that someone is going to have to do a full design of the front-to-end consideration of different drag and drop scenarios and come up with something that fits our particular system. We don't want to just copy what a file system does, because we have different advantages and disadvantages to a file system. I do tend to agree that it needs to be entirely internally consistent, and that it encourages people to use version control. It could be a simple as changing the between service button to something more like "Make new version", "Keep both files", "Skip", "Cancel" and use that here. Alternately, we could presume that people are going to want to version control, and ensure that there is an animation in the grid when something gets a new version to show what's happening.

It may also be that we need to make it really easy for people to pull an old version out into a new file. It could be that we need to make version control more visible. But I'm not convinced a single change for this one situation is going to fix whatever problems we have without introducing new problems.

**Comment by hmoco** [comment] 2015-07-14 18:51
I guess a solution, for the file tree interface at the very least, would be to add a "Upload new version" button when a file is selected. And then just uploading a new file with the same name is no longer the primary/only way of using version control, and thus a warning like the one mentioned by @brianjgeiger would make a lot of sense.

**Comment by jinluyuan** [comment] 2015-07-14 18:53
Since this is very controversial and may not have a clear best practice, can we put the information about versioning into the FAQ or Getting Started? We actually don't have any explanation of it other than this blurb:
![screen shot 2015-07-14 at 2 50 57 pm](https://cloud.githubusercontent.com/assets/8591162/8681826/c913cf42-2a37-11e5-953c-8d31e7015d4c.png)

We should have an explanation somewhere, even if it's not in the uploading process, that uploading a file of the same name produces a new version of the existing file and that versions are available in the Revisions pane.

**Comment by jlcohoon** [comment] 2015-07-14 18:55
Having to click a button reduces the speed with which you can upload a new version though. Unless I'm not understanding the process? Version control is one of our big selling points and making it difficult to do/hidden seems unwise. 

Also, FAQ isn't really the right spot because no one has actually ever asked about this. Getting started would be appropriate though.

**Comment by jinluyuan** [comment] 2015-07-14 19:06
Version control is definitely a great asset, but I think its user-friendliness could be improved upon. It's inconsistent across add-ons (reference my comment about Dataverse & Figshare not creating new versions), and the Revisions pane displays different version information depending on the add-on (e.g. Dropbox doesn't display Date & User, Google Drive doesn't display User, whereas GitHub & OSF Storage do both). Users should be warned thoroughly about how it works, and displaying that in Getting Started works well. I understand it's not an issue for most people now, but it might become one as the OSF becomes more intensively used.

**Comment by jlcohoon** [comment] 2015-07-14 19:14
I agree that it could be more user friendly. It is inconsistent across add-ons, but again that doesn't mean the add-on behavior is right. In fact, on Dropbox itself, they automatically replace files just like we do. Also agreed that the revisions pane should show the same information for all add-ons. I think that resolving those things would help alleviate any confusion users might experience (though with low add-on use right now, I think that confusion is limited).

I'm also about to put in a pull request to update the file language on the getting started page to include information about version control.

I don't agree, however, that a warning when adding a new file version is the way to resolve any of those issues. Since we haven't had questions from users and it is consistent with other services' behaviors, and because asking for confirmation implies that you are losing something instead of adding something, I don't think the extra modal is helpful. Sorry I'm being so contrarian :/

**Comment by jinluyuan** [comment] 2015-07-14 19:16
@jlcohoon I think putting the info on Getting Started is a good compromise. :smiley:

**Comment by hmoco** [comment] 2015-07-14 19:22
Alrighty so I will not continue working on this, at least for the time being

**Closed** 2015-10-28 15:42 UTC
Labels: 3 - hold, discuss, enhancement, JIRA, priority - medium
