### ISSUE TITLE
download count identical for distinct files containing underscores or periods 

### ISSUE THREAD

**Issue by jlcohoon** [CenterForOpenScience/osf.io#2281] opened 2015-03-23 13:50 UTC
<h4>Steps</h4>
1. Find a file with an underscore in the title and more than 0 downloads. I used this one: https://osf.io/8qc4x/
2. Download the file or make a new one, saving it with the same name, except swap out the underscore for a period (or vice versa). For instance, this file is title RPP_aaudl.R. You would rename it RPP.aaudl.R
3. Upload the new file to the OSF, in the same component.

<h4>Outcome</h4>
1. The two files will now be on that OSF component.
2. The two files each have the same download count, even though one was just uploaded and should have 0 downloads.
![screen shot 2015-03-23 at 9 38 35 am](https://cloud.githubusercontent.com/assets/4965832/6781168/f05e4ef0-d141-11e4-848d-8dc6f4059d3d.png)
3. After deleting the old file, the new file still has >0 downloads—the same number that the old file had.

<h4>Expected</h4>
1. The two files should both be on the OSF (correct, as is)
2. The two files should have different download counts. The new one should have 0 upon upload (presently not correct). The old one should have the same number it had prior to the upload of the new one (correct, as is)
3. Deleting one of the files should not affect the download count of the other (correct, as is).

**Comment by huangginny** [comment] 2015-03-25 14:01
@GaryKriebel Can you assign me to this issue?

**Comment by huangginny** [comment] 2015-03-25 15:02
The commit that causes the problem is 60f430a9ae1f36ba0edd16879508e07bb2f1447f

**Comment by huangginny** [comment] 2015-03-25 15:21
ready for review @lbanner @sloria

**Comment by sloria** [comment] 2015-03-26 15:29
Reopening, as the fix needed to be reverted to address https://github.com/CenterForOpenScience/osf.io/issues/2321 . We are looking into a more permanent fix for this now.

**Comment by sloria** [comment] 2015-03-26 15:40
OK, the more permanent solution will be a part of @chrisseto 's larger changes to the OSF Storage addon.

**Comment by lbanner** [comment] 2015-03-26 15:56
OK -- do we, @chrisseto, have time-frame estimate in proposal on that yet?

**Comment by chrisseto** [comment] 2015-03-26 16:15
@lbanner within next week.

**Comment by lbanner** [comment] 2015-03-26 16:18
OK -- great.

**Comment by chrisseto** [comment] 2015-03-26 18:40
#2327 Fixes this

**Closed** 2015-03-27 13:57 UTC
Labels: 5 - Pending Review, Bug: Production, Priority - High
