### ISSUE TITLE
[staging & production] Audio bar disappears.

### ISSUE THREAD

**Issue by jeg3tw** [CenterForOpenScience/osf.io#1686] opened 2015-02-02 17:43 UTC
Reported by @kushG on the 0.24 Trello board.

# Steps
1. Go to MFR project
2. Select bread-in-toaster.wav from files tab.

# Expected
There should be an audio bar with playing controls visible to user.
*seems to be a Firefox specific problem*

# Actual
Audio bar is visible for only seconds then disappears.

![](https://trello-attachments.s3.amazonaws.com/54ca8c82e32ce0c8578f985c/399x71/ec145ba3ea949a22a32529ad8cb6fc66/Screen_Shot_2015-01-29_at_2.38.05_PM.png)

![](https://trello-attachments.s3.amazonaws.com/54ca8c82e32ce0c8578f985c/760x399/acbe29a74a18d37635b2841540ac1a13/Screen_Shot_2015-01-29_at_2.38.17_PM.png)

![](https://trello-attachments.s3.amazonaws.com/54ca8c82e32ce0c8578f985c/763x198/4a1d1937178c05a48b213afa236900ed/Screen_Shot_2015-01-29_at_3.15.25_PM.png)

**Comment by lbanner** [comment] 2015-02-02 21:31
In Firefox - I was able to view + play .wav files. The player is a little less 'clean' then Chrome (frame displays through the time message), but it is functional.
![screen shot 2015-02-02 at 4 29 34 pm](https://cloud.githubusercontent.com/assets/2964829/6009561/e183bbf0-aaf8-11e4-8599-af83d2540257.png)

**Comment by kushG** [comment] 2015-02-02 21:38
@lbanner Strangely, the issue is only for that one file. @brianjgeiger was mentioning that this is a known firefox issue. I couldn't find that link though !

**Comment by brianjgeiger** [comment] 2015-02-02 21:40
http://www.tutorialspoint.com/cgi-bin/practice.cgi?file=html5-50.htm

@lbanner when you tested, did you just drag a wav file into firefox, or did you test through the MFR or something similar to the above link?

**Comment by brianjgeiger** [comment] 2015-02-02 21:41
Limited research indicates this might be solvable by passing more metadata into the audio tag, incidentally.

**Comment by brianjgeiger** [comment] 2015-02-02 21:43
No, this is likely the problem: "What's the bit depth on your WAV files? Firefox supports 8-bit and 16-bit PCM, but not other bit depths (12, 20, 24, 32)." http://stackoverflow.com/a/10406276

**Comment by lbanner** [comment] 2015-02-02 21:45
@brianjgeiger On OSF I searched for projects with .wav files and opened a few in a public project. FYI: Our MFR Testing Project is no longer .... any way we can we get it back on Staging?

**Comment by nanchen47** [comment] 2015-04-03 19:44
Since this problem only occurs in one file and probably a firefox special problem, close this one. Reopen if you can repo this problem.

**Closed by nanchen47** 2015-04-03 19:44 UTC
Labels: 1 - Deferred
