### ISSUE TITLE
[production] [bug] "Invalid Date" displayed for View-only Links

### ISSUE THREAD

**Issue by saradbowman** [CenterForOpenScience/osf.io#3232] opened 2015-06-19 17:56 UTC
Steps
-------
1. Go to a private project.
2. Create a view-only link.

Expected
------------
View-only link creation date will be displayed.

Actual
--------
"Invalid date" is displayed.

![screen shot 2015-06-19 at 1 47 43 pm](https://cloud.githubusercontent.com/assets/7749914/8259505/f81c2b10-168a-11e5-9673-6807d9a60ecb.png)

This happens for newly created projects with newly created view-only links, view-only links created long ago to projects created long ago, and on newly created view-only links to projects created long ago.

**Comment by GaryKriebel** [comment] 2015-06-22 19:13
I am seeing this as well.

Perhaps @nanchen47 will see the cause while looking at a different view-only link issue.

**Comment by nanchen47** [comment] 2015-07-01 22:30
The pr is already merged and deployed on production.

**Closed by nanchen47** 2015-07-01 22:30 UTC
Labels: 5 - pending review, bug: production, priority - medium
