### ISSUE TITLE
Presentation service conference logo not resizing properly

### ISSUE THREAD

**Issue by AndrewSallans** [CenterForOpenScience/osf.io#2397] opened 2015-04-05 01:26 UTC
![screen shot 2015-04-04 at 9 22 05 pm](https://cloud.githubusercontent.com/assets/2151933/6995361/b7c81354-db10-11e4-923f-1543fc379ed4.png)

This meeting ends today, and I think the organizers are promoting this service now, so getting a quick fix in would be ideal.

What you did (step by step)
* Went to https://osf.io/view/ASB2015/

Where does this happen on the OSF?
* https://osf.io/view/ASB2015/

What you expected
* Logo would resize to appropriate window dimensions

What actually happened
* Fixed logo size that spans much broader than the view in my window.

Potential causes
* Fixed rather than dynamic sizing on logo.

Suggest a solution
What will it look like when this issue is resolved?
* Dynamic sizing based on window size would probably be best.

cc: @jolene-esposito @saradbowman

**Comment by lbanner** [comment] 2015-04-05 02:10
Possible that the uploaded logo is just too large - and we don't auto size? Not sure how Presentation logos get into the app - but can we replace with a smaller logo? @sloria or @saradbowman ... Insight on the backend here?

**Comment by brianjgeiger** [comment] 2015-04-05 02:20
The problem is that the image has the class "image-responsive" and it should be "img-responsive". The following is how it should look.

![screen shot 2015-04-04 at 10 19 53 pm](https://cloud.githubusercontent.com/assets/6599111/6995460/ce59c646-db18-11e4-93cd-f04e4f5b4b0c.png)

**Comment by lbanner** [comment] 2015-04-05 02:46
@brianjgeiger --- who can make needed change? TY!

**Comment by brianjgeiger** [comment] 2015-04-05 02:56
Fixed in #2398

**Comment by lbanner** [comment] 2015-04-05 03:05
You da man @brianjgeiger - thank you - @sloria if you can review and deploy #2398 asap that'd be great - TY!

**Comment by AndrewSallans** [comment] 2015-04-05 03:06
Thanks for the fix, @brianjgeiger

**Closed** 2015-04-05 15:45 UTC
