### ISSUE TITLE
Broken link to https://www.cos.io/prereg

### ISSUE THREAD

**Issue by TomHardwicke** [CenterForOpenScience/osf.io#6459] opened 2016-10-23 11:37 UTC
## Steps
1. On https://osf.io/prereg/ click the 'preregistration' link in the first sentence which takes you to this page: https://www.cos.io/prereg
## Expected

Web page about pre-registration
## Actual

404 Not Found error

**Comment by saradbowman** [comment] 2016-10-28 19:40
@evomellor Can you take a look at this?

**Comment by evomellor** [comment] 2016-10-28 19:49
Correct. The link on osf.io/prereg leads to www.cos.io/prereg, which is a 404 when the www is included. Changing to https://cos.io/prereg should fix the error. 

VERY oddly, https://www.cos.io/ is the Open Research Badges partnerships page, whereas https://cos.io/ is our domain. This explains the error, as www.cos.io/prereg does not exist, but I have no idea how www.cos.io got mixed up with cos.io. Perhaps a DNS error?

**Comment by evomellor** [comment] 2016-10-28 19:50
I just ask @mattclark if he had thoughts about the cause of that.

**Comment by evomellor** [comment] 2016-10-28 20:51
It's fixed now, thanks @TomHardwicke for spotting and @mattclark for fixing :)

**Closed** 2018-05-09 23:08 UTC
