### ISSUE TITLE
[osf] CSV files not rendering

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3015] opened 2015-06-08 20:59 UTC
Steps:

Go to a project (https://osf.io/y2qi4/, https://osf.io/runys/, https://osf.io/zcmjp/)
Click on a .csv file in the project

Expected behavior:
The CSV should render.

Actual behavior:
![screenshot 2015-06-08 16 49 41](https://cloud.githubusercontent.com/assets/7332030/8045181/a645d644-0dff-11e5-9f4f-16d5616087cb.png)

This is a really weird error. It shows up in safari, chrome, and firefox, but not for all csv files (for example: https://osf.io/2jgqr/). But, I'm getting the error for csv files from different projects, and both in OSF storage and in the github add-on. So it seems to be something about the rendering, rather than a particular file.

**Comment by lbanner** [comment] 2015-06-10 13:17
@nicipfeiffer @caileyfitz -- are we replicating this?

**Comment by nicipfeiffer** [comment] 2015-06-10 14:27
@csoderberg I do not have access to the files you linked.  However, in checking my own .csv files I am able to render in OSF storage.

**Comment by GaryKriebel** [comment] 2015-06-10 15:01
I am able to render a .csv in my project as well.

**Comment by csoderberg** [comment] 2015-06-10 15:21
You guys should now have access to the 2nd link so you can see the error on
the system. Johanna is also getting yhe rendering error on the two other
rpp links.

Gary, as I mentioned, this isn't happening for all csv. But it is happening
for c svs from two separate projects that use osf storage and a file I
github.

**Comment by jlcohoon** [comment] 2015-06-10 15:24
The console is producing this error: 
![screen shot 2015-06-10 at 11 15 24 am](https://cloud.githubusercontent.com/assets/4965832/8086306/bb2ba0ca-0f62-11e5-82c7-c67bd7afa12a.png)

I tried uploading one of the files that isn't rendering to another component and it does work there. But I'm getting the same issues that Courtney is. The two files that she linked to that I have access to were both uploaded on different days in April and both have multiple versions. 

I then tried uploading another .csv file to that same component and it also didn't render: 
![screen shot 2015-06-10 at 11 23 58 am](https://cloud.githubusercontent.com/assets/4965832/8086398/38aba4fa-0f63-11e5-9348-48cc990f169f.png)

**Comment by jlcohoon** [comment] 2015-06-10 15:43
Just tried the same thing on the other project—I uploaded a new CSV and it didn't render either.

**Comment by nicipfeiffer** [comment] 2015-06-10 15:47
I am wondering if we are handling the 2 types differently...http://superuser.com/questions/302334/true-difference-between-excel-csv-and-standard-csv

**Comment by GaryKriebel** [comment] 2015-06-10 15:48
@csoderberg, @jlcohoon, @nicipfeiffer, 
The issue with at least one file (Direct Studies.csv) is the percent sign.

If you replace "%" with "percent", the file renders.

![screen shot 2015-06-10 at 11 47 08 am](https://cloud.githubusercontent.com/assets/9437946/8087003/773adba2-0f66-11e5-8930-ca78321ee8b3.png)

What special characters are in the other CSV files that are not rendering?

**Comment by jlcohoon** [comment] 2015-06-10 15:53
I'm not sure what they are supposed to be, but there definitely are some that aren't rendering properly

**Comment by GaryKriebel** [comment] 2015-06-10 15:56
Then we need to 
* download those files
* look at them, see if there is a % sign in them
* change them to "percent"
* upload to a test project to see if they render
* if they do not render, look for other special characters so those can be accounted for along with %

**Comment by jlcohoon** [comment] 2015-06-10 16:00
The files that I uploaded just now definitely don't have special characters in them though (sorry—I didn't realize that earlier). So it can't be that a % sign is the cause.

**Comment by GaryKriebel** [comment] 2015-06-10 16:14
@csoderberg ... what about the other files you are stating won't render?

**Comment by csoderberg** [comment] 2015-06-10 18:05
@GaryKriebel Like Johanna, I uploaded a new .csv file to the https://osf.io/js7y4/ project called test.csv, with no special characters (one column, 4 rows, with the content test, 1, 2, 3) and it won't render, so it' can't just be a percent sign or special characters issue since there weren't any in the new file. 

As for the two files in the RPP project, I downloaded one and even though it's called 'Copy of tilburg data 37 final.csv' on the osf it download as 'Copy of tilburg data 37 final.csv.txt' for some reason. The other one, there was a character with an tilda (GÕ_ttingen), which seemed to be causing the issue with that particular file. So taking out special characters seems to fix some, but not all problems.

But, per my and @jlcohoon issues with files that definitely don't have special characters, something else might be going on on top of special characters? I also tried upload the test.csv file into a brand new project, and it still won't render correctly there (https://osf.io/bfp8g/).

**Comment by GaryKriebel** [comment] 2015-06-10 19:47
@icereval and I got closer to identifying what may be happening.... he will give it a closer look on his local system.

**Comment by icereval** [comment] 2015-06-11 03:14
I've fixed a majority of the sides cases identified, however one remains where after editing the study2.csv in the editor and saving it becomes unable to render. I'll take a look at this in depth tomorrow, as I mentioned the other cases should be working, please verify, thanks.

**Comment by icereval** [comment] 2015-06-11 15:28
Issue has been resolved with changes made and released in mfr 0.2.0/1

**Closed by icereval** 2015-06-11 15:28 UTC
Labels: 2 - ready, bug: production, priority - high

**Comment by GaryKriebel** [comment] 2015-06-11 15:29
Thanks @icereval
