### ISSUE TITLE
[osf] editable files in github add-ons downloaded with .txt extension put on

### ISSUE THREAD

**Issue by csoderberg** [CenterForOpenScience/osf.io#3037] opened 2015-06-10 18:40 UTC
Go to a project (https://osf.io/x9ua5/) with files in a github repo that are rendered as text files (e.g. .md and .csv files). Download the file.

You would expect that they would download with the correct extension.

They actually download with a .txt extension tacked on, so you get .md.txt and .csv.txt. This does NOT happen on OSF storage. I have no tried other add-ons. But it happens for github and has happened for multiple projects. 

![screenshot 2015-06-10 14 39 20](https://cloud.githubusercontent.com/assets/7332030/8090909/8dc73e3e-0f7e-11e5-9052-ad01cff435c2.png)

**Comment by csoderberg** [comment] 2015-06-10 18:46
possibly related to #3015 (accordion to @nicipfeiffer )

**Comment by icereval** [comment] 2015-06-11 15:28
@chrisseto thoughts?

**Comment by chrisseto** [comment] 2015-06-15 19:48
Confirmed with @csoderberg this is only an issue in safari.

**Comment by chrisseto** [comment] 2015-06-15 19:50
See:
https://support.apple.com/kb/TA24293?locale=en_US
https://discussions.apple.com/thread/3955970
For more detail.

**Comment by lbanner** [comment] 2015-06-15 19:53
Ah -- and looks not to be our issue, correct? So suggest we close? But be aware? Other thoughts?

**Comment by brianjgeiger** [comment] 2015-06-15 19:53
But from a developer's standpoint, I'm pretty sure that means that we are sending the wrong MIME type.

**Comment by chrisseto** [comment] 2015-06-15 19:54
We're sending the correct mime, a md file is a text file.
Safari should not be renaming those files regardless.

**Comment by brianjgeiger** [comment] 2015-06-15 19:54
For example, https://www.drupal.org/node/803802

**Comment by brianjgeiger** [comment] 2015-06-15 19:57
https://github.com/CenterForOpenScience/osf.io/issues/382 may also give some insight.

**Comment by chrisseto** [comment] 2015-06-15 20:06
For the moment we are trusting whatever mime type the file storage service returns to us.
We could set mimetypes based off of file extension?

**Comment by brianjgeiger** [comment] 2015-06-15 20:09
Yeah, I mean, plusses and minuses on that. I think we shouldn't do it for all files, but I think we should for markdown?

**Comment by chrisseto** [comment] 2015-06-15 20:10
What's the reasoning behind that?

**Comment by chrisseto** [comment] 2015-06-15 21:26
Fixed as of https://github.com/CenterForOpenScience/waterbutler/releases/tag/0.6.2
Deployed in production but not staging

**Comment by chrisseto** [comment] 2015-06-16 12:50
@lbanner Could you confirm and close this issue?

**Closed** 2015-06-16 13:26 UTC
Labels: 2 - ready, bug: production, priority - high
