### ISSUE TITLE
Statistics page recursive loading problem

### ISSUE THREAD

**Issue by mehanig** [CenterForOpenScience/osf.io#2659] opened 2015-05-07 05:03 UTC
<h1>Steps</h1>

1) Go to https://osf.io/4znzp/statistics/
2) Go to Widgets & Dashboard -> SEO -> Top Keywords for Page URL 
3) Click href link
4) Wait for new instance of OSF.io inside div
5) Repeat from 1

<h1>Expected</h1>
I would expect that whole page reloads or new tab opens

<h1>Actual</h1>
It loads same page but inside div
![screen shot 2015-05-07 at 07 46 02](https://cloud.githubusercontent.com/assets/5033274/7508791/717a13fa-f48f-11e4-9b2d-3d65cedecece.png)

<h1>Possible Cause</h1>
Dashboards plugin JS settings

<h1>Possible Solutions</h1>
Probably adding TARGET="_blank" to all links inside widgets text can help

**Comment by lbanner** [comment] 2015-05-07 19:24
Thank you for the catch @mehanig  ... @nicipfeiffer Can you recreate? And then we can get this assigned. TY!

**Comment by ticklemepierce** [comment] 2015-05-26 20:00
I am unable to reproduce on production based on the above steps unless I am interpreting this incorrectly.

**Comment by mehanig** [comment] 2015-05-26 21:24
@ticklemepierce  no prob, I recorded screencast  ->https://pdlvimeocdn-a.akamaihd.net/70409/326/372111030.mp4?token2=1432689824_08c341430b8b5e3554bfc9c6d8aefed2&aksessionid=096496ad4fcd746299d59b3456e86d5979de1b181432675424

**Comment by hmoco** [comment] 2015-05-28 21:13
@mehanig I have also been unable to reproduce this issue. I have tried in safari, chrome and firefox. Clicking on a link, in both the widget preview window for 'Top Records for Page URL' and when the widget is located in the page, send me to a new tab, and does not cause the 'page within page' problem seen on the screenshot. Will also try on I.E. and report back. Also, the screencast link seems to be broken.

**Comment by mehanig** [comment] 2015-05-28 21:18
@hmoco  I tried it only chrome. Osx.
Sorry for broken link, it worked yesterday.
https://yadi.sk/d/EdWOOAeKgw44Q I re-uploaded it.
Anyway, if you can't reproduce it than it's probably mine bug and Issue could be closed.

**Comment by hmoco** [comment] 2015-05-28 21:28
Hah, yes that does happen when clicking that link specifically. That is very interesting. I will work on this. Thank you!

**Comment by hmoco** [comment] 2015-05-28 21:33
![screen shot 2015-05-28 at 5 32 19 pm](https://cloud.githubusercontent.com/assets/6268982/7871698/95e9bcfa-055f-11e5-9233-7810bd4f704a.png)

**Comment by mehanig** [comment] 2015-05-28 21:34
@hmoco  Yes ;) looks great!

**Comment by hmoco** [comment] 2015-05-29 16:58
So this is apparently a problem that is known, and piwik needs to be updated. I talked to Lyndsy about it and it will probably be fixed by him when he gets to updating the stats page.

**Comment by lbanner** [comment] 2015-05-29 17:00
I will hand it off to @lyndsysimon . TY.

**Comment by lyndsysimon** [comment] 2015-06-15 18:40
This update will require deploying a new production Piwik instance - I've remove it from our issues sprint milestone because it's a bit too large in scope.

**Closed** 2015-10-28 15:28 UTC
Labels: 4 - working, bug: production, community, intern, level 1, priority - high
