### ISSUE TITLE
[staging & production] Read + Write contributors cannot enable add-ons

### ISSUE THREAD

**Issue by caileyfitz** [CenterForOpenScience/osf.io#2665] opened 2015-05-07 18:59 UTC
# Steps
1. On staging or production, go to a project on which you have admin access
2. As User A (user you logged in as), go to the Setting page and disable all add-ons
3. Go to the Sharing tab
4. Add a second user that you have access to, User B, as a read + write contributor
5. In another window (private or incognito), log in as User B
6. As User B, go to the project on which you were just added as a contributor
7. Go to the Settings tab
8. Notice the options in the navigation widget on the upper-left hand side of the screen 
9. Check a box next to an add-on to enable the add-on
10. With the box checked, press Submit
11. After page reload, check if the add-on was enabled
12. Return to the first screen as User A
13. As User A, enable and configure at least one add-on
14. Return to the second screen as User B
15. As User B, now notice the options in the navigation widget on the upper-left hand side of the screen 
16. Again, attempt to enable an add-on
17. Go to the Configure Add-ons widget and Deauthorize an add-on

# Expected
I expect that a user with read + write permissions would be able to enable and configure add-ons for a project on which they are a contributor. 

# Actual
Here are the actual outcomes for the following steps above:
- Step 8. With no add-ons configured, User B only has two options in the navigation widget: 
![screen shot 2015-05-07 at 2 42 03 pm](https://cloud.githubusercontent.com/assets/5975444/7523083/4d287374-f4c7-11e4-8019-8cb0db2a8c6d.png)
- Step 9. No terms modal appears upon checking the box, even though it should if the user really has permission to enable add-ons. 
- Step 11. The box does not remain checked upon refresh. This is the main issue because a non-admin user does not currently have the ability to enable an add-on.
- Step 15. With at least one add-on configured, three options are available:
![screen shot 2015-05-07 at 2 53 18 pm](https://cloud.githubusercontent.com/assets/5975444/7523299/d393e4ec-f4c8-11e4-801f-195251d06a43.png)
- Step 16. User B still cannot enable an add-on.
- Step 17. Despite not being able to enable an add-on, User B can deauthorize and configure an add-on, which is strange. 

Tagging @sloria @GaryKriebel @lbanner @nanchen47 because I think this needs to be addressed ASAP.

**Comment by lbanner** [comment] 2015-05-07 19:19
Not sure we have a full outline of user-levels of access per designation. But I actually do not think a user w/ "read + write" access should be able to change or enable add-ons. I think that should sit at Admin level. "read + write" should give the ability to upload and change files and edit Wiki. More insight here on user-levels?

**Comment by caileyfitz** [comment] 2015-05-07 19:39
I talked to @sloria about this, and he said it was a bug that read + write is not able to configure add-ons. I think it makes sense for read + write to be able to enable/configure add-ons in cases where there is one admin who has access to everything (adding contributors, configuring project) and has read + write contributors who should be able to connect their own accounts to share their data with other collaborators.

**Comment by brianjgeiger** [comment] 2015-05-07 19:46
Is it expected that people who do not own the add-on authorization would be able to configure that addon? So if I add my dropbox, nobody else should be able to change those dropbox settings, right? At most, they should be able delete the credentials from the project and add their own, but they should not be able to change the dropbox folder, true?

**Comment by GaryKriebel** [comment] 2015-05-07 19:53
I agree with Brian's last two points.

**Comment by caileyfitz** [comment] 2015-05-07 19:55
@brianjgeiger Currently, another user cannot change your add-on configurations. I can only deauthorize you and then authorize myself.

**Comment by lbanner** [comment] 2015-05-08 02:22
Which also seems potentially problematic, no? .... multiple read + write contributors on a project battling over whose add-on gets precedence? I don't know, maybe that is how research collaborators may work -- each adding their own storage spot, but with potential conflicts -- still, this is why I'd think choice of add-on (and control) might better reside w/the Project Admin.

**Comment by caileyfitz** [comment] 2015-05-08 13:19
@lbanner You could say the same thing about multiple admins. Then the *admins* would be battling over add-on precedence. I don't really think it's an issue though. Especially with collaborations between multiple schools, we would want multiple contributors to be able to authorize add-ons.

**Comment by caileyfitz** [comment] 2015-05-08 17:46
Whatever the decision is about this, I think it needs to be made sooner rather than later because our UI is inconsistent right now. You can check a box and press the Submit button and nothing happens. If you do not have that ability, you should not see that option. Likewise, if you see that option, you should have that ability.

**Comment by caileyfitz** [comment] 2015-05-14 14:49
Commenting again to revive this. Deferring to @bnosek, @sloria, and @JeffSpies for a final decision, but I think a fix needs to happen soon.

**Comment by bnosek** [comment] 2015-05-14 14:57
Yes, read+write users should be able to enable their add-ons in order to share their work with other members of the team.

**Comment by caileyfitz** [comment] 2015-05-14 14:57
Thanks @bnosek

**Comment by chennan47** [comment] 2015-05-14 15:04
I think perhaps we need some documentation for the privileges for different level of contributors for future reference. @sloria @GaryKriebel

**Comment by caileyfitz** [comment] 2015-05-14 15:07
Here is the current documentation we have, listed under 'Contributors' on the Getting Started page:
![screen shot 2015-05-14 at 11 06 06 am](https://cloud.githubusercontent.com/assets/5975444/7634510/5ae0462e-fa29-11e4-8741-e523c3d3a26a.png)

**Comment by sloria** [comment] 2015-05-14 15:15
Spoke with @JeffSpies: he agreed that read+write should be able to add add-ons. @chennan47 Can you implement this when you get the chance?

**Comment by chennan47** [comment] 2015-05-14 15:19
@sloria will do

**Comment by nanchen47** [comment] 2015-05-20 19:10
The pr has been merged in and the problem is solved on production.

**Closed by nanchen47** 2015-05-20 19:10 UTC
Labels: 5 - Pending Review, Bug: Production, Priority - Medium
